<p>
	<a class="close"><i class="icon-close"></i></a>
	<?php if ($this->sender == AjaxController::SENDER_SCORE or $this->sender == AjaxController::SENDER_SCORE_TIME): ?>
		<?php if ($this->score == 0): ?>
			Unrated titles
		<?php else: ?>
			Titles rated with <?php echo $this->score ?>
		<?php endif ?>

	<?php elseif ($this->sender == AjaxController::SENDER_SCORE or $this->sender == AjaxController::SENDER_SCORE_LENGTH): ?>
		<?php if ($this->length == '?'): ?>
			Titles with unknown length
		<?php else: ?>
			Titles of length <?php echo $this->length ?>
		<?php endif ?>

	<?php elseif ($this->sender == AjaxController::SENDER_YEAR or $this->sender == AjaxController::SENDER_DECADE): ?>
		<?php echo ucfirst($this->mgHelper->textAM()) ?>
		&nbsp;from&nbsp;
		<?php if ($this->sender == AjaxController::SENDER_YEAR): ?>
			<?php echo $this->year ?: 'unknown year' ?>
		<?php else: ?>
			<?php echo $this->decade ? $this->decade . 's' : 'unknown decade' ?>
		<?php endif ?>

	<?php elseif ($this->sender == AjaxController::SENDER_GENRE): ?>
		<?php echo ucfirst($this->mgHelper->textAM()) ?>
		&nbsp;tagged as&nbsp;
		<?php echo ucfirst($this->genre->getName()) ?>

	<?php elseif ($this->sender == AjaxController::SENDER_CREATOR): ?>
		<?php echo ucfirst($this->mgHelper->textAM()) ?>
		&nbsp;from&nbsp;
		<?php echo $this->creator->getName() ?>

	<?php elseif ($this->sender == AjaxController::SENDER_SUB_TYPE): ?>
		Non-planned <?php echo $this->mgHelper->textAM() ?>
		&nbsp;in&nbsp;
		<?php echo ChibiRegistry::getHelper('mg')->textSubType($this->subType) ?>
		&nbsp;category

	<?php elseif ($this->sender == AjaxController::SENDER_DAILY_ACTIVITY): ?>
		<?php echo $this->am == AMModel::TYPE_MANGA ? 'Chapters' : 'Episodes' ?>
		&nbsp;from&nbsp;
		<?php if ($this->daysAgo == 0): ?>
			today
		<?php elseif ($this->daysAgo == 1): ?>
			yesterday
		<?php else: ?>
			<?php echo $this->daysAgo ?> days ago
		<?php endif ?>

	<?php elseif ($this->sender == AjaxController::SENDER_MONTHLY_ACTIVITY): ?>
		<?php if ($this->monthPeriod == '?'): ?>
			Titles with unspecified completion or start date
		<?php else: ?>
			Titles from <?php echo $this->monthPeriod ?>
		<?php endif ?>

	<?php elseif ($this->sender == AjaxController::SENDER_FRANCHISES): ?>
		Franchises consisting of at least two titles

	<?php elseif ($this->sender == AjaxController::SENDER_MISMATCHED_EPS): ?>
		<?php if ($this->am == AMModel::TYPE_ANIME): ?>
			Titles that have mismatching episode count
		<?php else: ?>
			Titles that have mismatching chapter count
		<?php endif ?>
	<?php endif ?>:

	<?php if (!empty($this->entries)): ?>
		&nbsp;(<?php echo count($this->entries) ?>
			<?php if (isset($this->meanScore)): ?>
				<?php if (!$this->meanScore): ?>
					, none rated
				<?php else: ?>
					, mean score: <?php echo sprintf('%.02f', $this->meanScore) ?>
				<?php endif ?>
			<?php endif ?>
		)
	<?php endif ?>
</p>


<?php if (empty($this->entries)): ?>
	<?php if (($this->sender == AjaxController::SENDER_SCORE or $this->sender == AjaxController::SENDER_SCORE_TIME) and $this->score == 0): ?>
		<p>Horray! No unrated titles.</p>
	<?php else: ?>
		<p>None!</p>
	<?php endif ?>
<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
	<p>Can&rsquo;t show you titles from a private list.</p>
<?php else: ?>

	<?php if ($this->sender == AjaxController::SENDER_FRANCHISES): ?>
		<ol class="franchises">
			<?php foreach ($this->entries as $franchise): ?>
				<li>
					<?php foreach ($franchise->ownEntries as $entry): ?>
						<?php $amEntry = $entry->getAMEntry(); ?>
						<a href="http://myanimelist.net/<?php echo $this->mgHelper->textAM() ?>/<?php echo $amEntry->getID() ?>">
							<?php echo $amEntry->getTitle() ?>
						</a>
						<span class="details">&nbsp;(
							<?php if ($this->am == AMModel::TYPE_ANIME): ?>
								<?php echo ChibiRegistry::getHelper('mg')->textEpisodes($amEntry->getEpisodeCount() ?: $entry->getCompletedEpisodes() . '+', true) ?>
							<?php elseif ($this->am == AMModel::TYPE_MANGA): ?>
								<?php echo ChibiRegistry::getHelper('mg')->textChapters($amEntry->getChapterCount() ?: $entry->getCompletedChapters() . '+', true) ?>
							<?php endif ?>,&nbsp;
							<?php if ($entry->getScore() == 0): ?>
								not rated
							<?php else: ?>
								rated&nbsp;with&nbsp;<?php echo $entry->getScore() ?>
							<?php endif ?>
						)</span><br>
					<?php endforeach ?>
					<span class="details">(<?php echo count($franchise->ownEntries) ?> titles, 
						<?php if ($franchise->meanScore): ?>
							mean score: <?php printf('%.02f', $franchise->meanScore) ?>
						<?php else: ?>
							none rated
						<?php endif ?>
					)</span>
				</li>
			<?php endforeach ?>
		</ol>

	<?php else: ?>
		<ul>
			<?php foreach ($this->entries as $entry): ?>
				<?php $amEntry = $entry->getAMEntry() ?>
				<li>
					<a href="http://myanimelist.net/<?php echo $this->mgHelper->textAM() ?>/<?php echo $amEntry->getID() ?>">
						<?php echo $amEntry->getTitle() ?>
					</a>
					<span class="details">&nbsp;(
						<?php if ($this->sender == AjaxController::SENDER_SCORE or $this->sender == AjaxController::SENDER_SCORE_TIME): ?>
							<?php echo $entry->getCompletedDuration() ?> min.
						<?php elseif (in_array($this->sender, [AjaxController::SENDER_YEAR, AjaxController::SENDER_DECADE, AjaxController::SENDER_GENRE, AjaxController::SENDER_CREATOR, AjaxController::SENDER_SUB_TYPE, AjaxController::SENDER_SCORE_LENGTH])): ?>
							<!--<?php echo $entry->getCompletedDuration() ?>&nbsp;min.,&nbsp;-->
							<?php if ($entry->getScore() == 0): ?>
								not rated
							<?php else: ?>
								rated with <?php echo $entry->getScore() ?>
							<?php endif ?>
						<?php elseif ($this->sender == AjaxController::SENDER_DAILY_ACTIVITY): ?>
							<?php if ($entry->getType() == AMModel::TYPE_MANGA): ?>
								chap. <?php echo $entry->getChapter() ?>
							<?php else: ?>
								ep. <?php echo $entry->getEpisode() ?>
							<?php endif ?>
							&nbsp;&ndash;&nbsp;<?php echo date('M jS, H:i', $entry->getTimestamp()) ?>&nbsp;UTC
						<?php elseif ($this->sender == AjaxController::SENDER_MONTHLY_ACTIVITY): ?>
							<?php echo $entry->getStartDate() ?>&nbsp;&mdash;&nbsp;<?php echo $entry->getFinishDate() ?>
						<?php elseif ($this->sender == AjaxController::SENDER_MISMATCHED_EPS): ?>
							<?php if ($entry->getType() == AMModel::TYPE_MANGA): ?>
								on your list: <?php echo $entry->getCompletedChapters() ?>,&nbsp;
								<?php if ($entry->getAMEntry()->getStatus() == AMEntry::STATUS_PUBLISHING): ?>
									but it&rsquo;s still publishing
								<?php else: ?>
									should be <?php echo ChibiRegistry::getHelper('mg')->textChapters($entry->getAMEntry()->getChapterCount()) ?>
								<?php endif ?>
							<?php else: ?>
								on your list: <?php echo $entry->getCompletedEpisodes() ?>,&nbsp;
								<?php if ($entry->getAMEntry()->getStatus() == AMEntry::STATUS_PUBLISHING): ?>
									but it&rsquo;s still airing
								<?php else: ?>
									should be  <?php echo ChibiRegistry::getHelper('mg')->textEpisodes($entry->getAMEntry()->getEpisodeCount()) ?>
								<?php endif ?>
							<?php endif ?>
						<?php endif ?>
					)</span>
				</li>
			<?php endforeach ?>
		</ul>

	<?php endif ?>
<?php endif ?>
