<?php if (!empty($e['others']) and count($e['others']) == 1): ?>
	<?php $e2 = reset($e['others']) ?>
	<?php if ($e['user']['score'] > $e2['user']['score'] and $e2['user']['score'] > 0): ?>
		<td class="score higher-score">
	<?php elseif ($e['user']['score'] < $e2['user']['score'] and $e['user']['score'] > 0): ?>
		<td class="score lower-score">
	<?php else: ?>
		<td class="score same-score">
	<?php endif ?>
<?php else: ?>
	<td class="score">
<?php endif ?>
	<?php if (empty($e['user']['score'])): ?>
		-
	<?php else: ?>
		<?php echo $e['user']['score'] ?>
	<?php endif ?>
</td>

