<td class="status">
	<i
	<?php if ($e['user']['status'] == UserModel::USER_LIST_STATUS_PLANNED): ?>
		data-title="Planned" class="icon-schedule"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_DROPPED): ?>
		data-title="Dropped" class="icon-cross"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_WATCHING): ?>
		data-title="Watching" class="icon-eye"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_ONHOLD): ?>
		data-title="On-hold" class="icon-hourglass"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_COMPLETED): ?>
		data-title="Completed" class="icon-tick"
	<?php endif ?>
		rel="tooltip"
	>
	</i>
</td>
