<td class="status">
	<i
	<?php if ($e['user']['status'] == UserModel::USER_LIST_STATUS_PLANNED): ?>
		data-title="Planned" class="icon-schedule tooltipable"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_DROPPED): ?>
		data-title="Dropped" class="icon-cross tooltipable"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_WATCHING): ?>
		data-title="Watching" class="icon-eye tooltipable"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_ONHOLD): ?>
		data-title="On-hold" class="icon-hourglass tooltipable"
	<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_COMPLETED): ?>
		data-title="Completed" class="icon-tick tooltipable"
	<?php endif ?>
	></i>
</td>
