<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<?php echo $this->headHelper->render() ?>
</head>
<body>
	<?php if ($this->view->controllerName == 'stats' and count($this->view->userNames) > 1): ?>
	<div id="main-wrapper" class="compare-mode">
	<?php else: ?>
	<div id="main-wrapper">
	<?php endif ?>
		<div id="header">
			<h1>
				<a href="<?php echo $this->urlHelper->url('') ?>">
					<span>MALgraph</span>
				</a>
			</h1>
			<form class="waitable" id="search" action="<?php echo $this->urlHelper->url('stats/search') ?>" method="post">
				<?php if (!empty($this->view->userNames)): ?>
					<input type="hidden" name="active-user-name" value="<?php echo reset($this->view->userNames) ?>">
				<?php endif ?>
				<?php if (!empty($this->view->am)): ?>
					<input type="hidden" name="am" value="<?php echo $this->view->am ?>">
				<?php endif ?>
				<div class="control-group input-append">
					<input type="search" name="user-name">
					<button title="Search" name="submit" value="search" class="btn" type="submit"><i class="icon-search"></i></button>
					<?php if ($this->view->controllerName == 'stats'): ?>
						<button title="Compare" name="submit" value="compare" class="btn" type="submit"><i class="icon-compare"></i></button>
					<?php else: ?>
						<button title="Compare" name="submit" value="compare" class="btn disabled" disabled="disabled" type="submit"><i class="icon-compare"></i></button>
					<?php endif ?>
				</div>
			</form>
			<div class="clear"></div>
		</div>

		<div id="main">
			<?php if ($this->view->controllerName == 'stats'): ?>
				<div id="menu">
					<ul class="am">
						<?php foreach ([UserModel::USER_LIST_TYPE_ANIME, UserModel::USER_LIST_TYPE_MANGA] as $type): ?>
							<?php if ($this->view->am == $type): ?>
								<li class="active">
							<?php else: ?>
								<li>
							<?php endif ?>
								<a href="<?php echo $this->urlHelper->url('stats/switch-am', ['am' => $type, 'action' => $this->view->actionName, 'u' => $this->view->userNames]) ?>">
									<i class="icon-<?php echo $type ?>"></i>
								</a>
							</li>
						<?php endforeach ?>
					</ul>
					<?php
						$menu = [
							['controller' => 'stats', 'action' => 'profile', 'text' => 'Profile'],
							['controller' => 'stats', 'action' => 'list', 'text' => 'List'],
							['controller' => 'stats', 'action' => 'scores', 'text' => 'Scores'],
							['controller' => 'stats', 'action' => 'history', 'text' => 'History'],
							['controller' => 'stats', 'action' => 'favs', 'text' => 'Favorites'],
							['controller' => 'stats', 'action' => 'misc', 'text' => 'Miscellaneous'],
							['controller' => 'stats', 'action' => 'sug', 'text' => 'Suggestions'],
							['controller' => 'stats', 'action' => 'json', 'text' => 'JSON'],
						];
					?>
					<ul>
						<?php foreach ($menu as $item): ?>
							<?php if ($this->view->controllerName == $item['controller'] and $this->view->actionName == $item['action']): ?>
								<li class="active">
							<?php else: ?>
								<li>
							<?php endif ?>
								<a class="waitable" href="<?php echo $this->urlHelper->url($item['controller'] . '/' . $item['action'], ['u' => $this->view->userNames, 'am' => $this->view->am]) ?>">
									<?php echo $item['text'] ?>
								</a>
							</li>
						<?php endforeach ?>
					</ul>
				</div>
			<?php endif ?>

			<div id="content">
				<?php echo $this->view->render() ?>
			</div>
			<div class="clear"></div>
		</div>

		<div id="footer">
			<p><a href="<?php echo $this->urlHelper->url('index/about') ?>">About</a></p>
			<p><a href="<?php echo $this->urlHelper->url('index/privacy') ?>">Privacy policy</a></p>
			<p>Suggestions? Questions? Visit the <a href="http://myanimelist.net/clubs.php?cid=30017">MALgraph club</a> and ask!</p>
		</div>
	</div>

	<div id="glider">
		<div>
			<div class="target"></div>
			<p></p>
		</div>
	</div>
</body>
</html>
