<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<?php echo $this->headHelper->render() ?>
</head>
<body>
	<div id="main-wrapper">
		<div id="header">
			<h1>
				<a href="<?php echo $this->urlHelper->url('/') ?>">
				MALgraph
				</a>
			</h1>
		</div>
		<div id="content">
			<?php echo $this->view->render() ?>
		</div>
		<div id="footer">
			<p><a href="<?php echo $this->urlHelper->url('/index/about') ?>">About</a></p>
			<p><a href="<?php echo $this->urlHelper->url('/index/privacy') ?>">Privacy policy</a></p>
			<p>Suggestions? Questions? Visit the <a href="http://myanimelist.net/clubs.php?cid=30017">MALgraph club</a> and ask!</p>
		</div>
	</div>
</body>
</html>
