<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<?php echo $this->headHelper->render() ?>
</head>
<body>
	<h1>It works!</h1>
	<p>Layout code was rendered in <?php echo __FILE__ ?></p>
	<p>You are browsing <?php echo $_SERVER['REQUEST_URI'] ?></p>
	<div>
		<?php echo $this->view->render() ?>
	</div>
	<p>Current controller: <?php echo $this->config->chibi->runtime->controllerName ?><br>
	Current action: <?php echo $this->config->chibi->runtime->actionName ?><br>
</body>
</html>
