<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<?php echo HeadHelper::render() ?>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta property="og:title" content="<?php echo HeadHelper::getTitle() ?>">
	<meta property="og:description" content="<?php echo HeadHelper::getDescription() ?>">
	<meta property="og:image" content="<?php echo UrlHelper::url('media/img/logo3.png') ?>">
	<meta property="og:url" content="<?php echo ChibiRegistry::getHelper('mg')->currentUrl() ?>">
	<meta property="og:site_name" content="MALgraph" />
</head>
<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
	<?php if (count(ChibiRegistry::getView()->userNames) > 1): ?>
		<body class="user-mode compare-mode" data-am="<?php echo ChibiRegistry::getView()->am ?>">
	<?php else: ?>
		<body class="user-mode" data-am="<?php echo ChibiRegistry::getView()->am ?>">
	<?php endif ?>
<?php else: ?>
	<body>
<?php endif ?>
	<div id="header">
		<div class="main-wrapper">
			<div id="no-script">
				JavaScript is disabled. Consider enabling it to get positive user experience.
			</div>
			<script type="text/javascript">
				$('#no-script').hide()
			</script>
			<ul id="top-nav">
				<li id="logo">
					<a href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('index', 'index') ?>">
						<span>MALgraph</span>
					</a>
				</li>
				<li><a href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('index', 'about') ?>">About</a></li>
				<li><a href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('index', 'privacy') ?>">Privacy</a></li>
				<li><a href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('index', 'globals') ?>">Globals</a></li>
			</ul>
			<form class="waitable search" action="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('index', 'search') ?>" method="post">
				<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
					<?php foreach (ChibiRegistry::getView()->userNames as $userName): ?>
						<input type="hidden" name="user-names[]" value="<?php echo $userName ?>">
					<?php endforeach ?>
					<input type="hidden" name="action-name" value="<?php echo ChibiRegistry::getView()->actionName ?>">
				<?php endif ?>
				<?php if (!empty(ChibiRegistry::getView()->am)): ?>
					<input type="hidden" name="am" value="<?php echo ChibiRegistry::getView()->am ?>">
				<?php endif ?>
				<div class="control-group input-append">
					<input type="search" name="user-names[]">
					<button data-tooltip="Search" name="submit" value="search" type="submit" class="btn"><i class="icon-search"></i></button>
					<button data-tooltip="Compare" name="submit" value="compare" type="submit"
						<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
							class="btn"
						<?php else: ?>
							class="btn disabled" disabled="disabled"
						<?php endif ?>
						><i class="icon-compare"></i>
					</button>
				</div>
			</form>
			<div class="clear"></div>
		</div>
	</div>


	<?php if (ChibiRegistry::getView()->controllerName == 'stats' and ChibiConfig::getInstance()->misc->googleAdsEnabled): ?>
		<div id="google-ads">
			<script type="text/javascript">
				google_ad_client = "ca-pub-4861833348203348"; /* malgraph3-header */
				google_ad_slot = "3987532635";
				google_ad_width = 728;
				google_ad_height = 90;
			</script>
			<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
		</div>
	<?php endif ?>

	<div class="main-wrapper">
		<div id="menu-wrapper">
			<div id="menu">
				<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
					<div class="user-pics">
						<?php foreach (ChibiRegistry::getView()->users as $i => $user): ?>
							<div class="user-pic-wrapper user<?php echo $user->getRuntimeID() ?>">
								<div class="user-pic">
									<a href="<?php echo ChibiRegistry::GetHelper('mg')->constructUrl('stats', 'profile') ?>">
									<?php if ($user->isAnonymous() or $user->getUserData()->getProfilePictureURL() == null): ?>
										<img class="profile unavailable" alt="No profile picture" src="<?php echo UrlHelper::url('media/img/pixel.gif') ?>">
									<?php else: ?>
										<img class="profile" alt="<?php echo $user->getPublicName() ?>&rsquo;s profile picture" src="<?php echo UrlHelper::url('media/img/pixel.gif') ?>" style="background-image: url('<?php echo $user->getUserData()->getProfilePictureURL() ?>')">
									<?php endif ?>
									</a>
								</div>
								<p class="user-nick">
									<a href="<?php echo ChibiRegistry::GetHelper('mg')->constructUrl('stats', 'profile') ?>">
										<?php echo $user->getPublicName() ?>
									</a>
								</p>
							</div>

							<?php if ($i == 1 and count(ChibiRegistry::getView()->users) > 1): ?>
								<a data-tooltip="Swap profiles" id="switcher" href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl(null, null, [], [end(ChibiRegistry::getView()->userNames), reset(ChibiRegistry::getView()->userNames)]) ?>">
									<i class="icon-switch"></i>
								</a>
							<?php endif ?>
						<?php endforeach ?>
						<div class="clear"></div>
					</div>

					<?php
						$menu = [
							['controller' => 'stats', 'action' => 'list', 'text' => 'List'],
							['controller' => 'stats', 'action' => 'rati', 'text' => 'Ratings'],
							['controller' => 'stats', 'action' => 'acti', 'text' => 'Activity'],
							['controller' => 'stats', 'action' => 'favs', 'text' => 'Favorites'],
							['controller' => 'stats', 'action' => 'sug', 'text' => 'Suggestions'],
							['controller' => 'stats', 'action' => 'achi', 'text' => 'Achievements'],
						];
					?>
					<div class="actions">
						<?php foreach (AMModel::getTypes() as $am): ?>
							<div>
								<p><?php echo ucfirst(ChibiRegistry::getHelper('mg')->textAM($am)) ?></p>
								<ul class="action">
									<?php foreach ($menu as $item): ?>
										<?php if (ChibiRegistry::getView()->actionName == $item['action'] and ChibiRegistry::getView()->am == $am): ?>
											<li class="active">
										<?php else: ?>
											<li>
										<?php endif ?>
											<a class="waitable" href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl('stats', $item['action'], [], null, $am) ?>">
												<?php echo $item['text'] ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</div>
						<?php endforeach ?>
						<div class="clear"></div>
					</div>

					<div class="share">
						<p>Share:</p>
						<ul>
							<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
								<li>
									<a data-tooltip="Anonymize current profile|(for anonymous sharing)" href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl(null, null, [], array_map(function($u) { return $u->getAnonymousName(); }, ChibiRegistry::getView()->users)) ?>">
										<i class="icon-anonymize"></i>
									</a>
								</li>
							<?php endif ?>
							<li>
								<a data-tooltip="Share on Twitter" href="https://twitter.com/intent/tweet?url=<?php echo rawurlencode(ChibiRegistry::getHelper('mg')->currenturl()) ?>">
									<i class="icon-twitter"></i>
								</a>
							</li>
							<li>
								<a data-tooltip="Share on Facebook" href="http://www.facebook.com/sharer.php?u=<?php echo rawurlencode(ChibiRegistry::getHelper('mg')->currentUrl()) ?>&amp;t=Share+MALgraph">
									<i class="icon-facebook"></i>
								</a>
							</li>
						</ul>
					</div>

				<?php else: ?>
					<ul class="action">
						<li class="back">
							<a href="javascript:history.go(-1)">
								<i class="icon-go-back"></i>
								Go back
							</a>
						</li>
					</ul>
				<?php endif ?>
			</div>

			<div class="clear"></div>
		</div>

		<div id="main">
			<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
				<?php function iterateUsers($callback) {
					$keys = (array_keys(ChibiRegistry::getView()->users));
					echo '<div class="users">';
					foreach ($keys as $i => $k) {
						$user = ChibiRegistry::getView()->users[$k];
						if (count(ChibiRegistry::getview()->users) > 1) {
							$otherUser = ChibiRegistry::getView()->users[$keys[1 - $i]];
						} else {
							$otherUser = null;
						}
						echo '<div class="user-wrapper">';
						if ($user->isAnonymous()) {
							echo '<div class="user anonymous user-' . $user->getRuntimeID() . '" data-user-name="' . $user->getLinkableName() . '">';
						} else {
							echo '<div class="user user-' . $user->getRuntimeID() . '" data-user-name="' . $user->getLinkableName() . '">';
						}
						$callback($user, $otherUser);
						echo '</div>';
						echo '</div>';
					}
					echo '<div class="clear"></div>';
					echo '</div>';
				} ?>

				<?php echo ChibiRegistry::getView()->render() ?>
			<?php else: ?>
				<?php echo ChibiRegistry::getView()->render() ?>
			<?php endif ?>
		</div>

		<div class="clear"></div>
	</div>

	<p class="load-time">
		<?php printf('%.02f', microtime(true) - ChibiConfig::getInstance()->chibi->runtime->timeStarted) ?>s
		&nbsp;|&nbsp;
		<?php echo date('M d Y, H:i:s') ?> UTC
	</p>

	<?php if (ChibiRegistry::getView()->controllerName == 'stats'): ?>
		<script type="text/javascript">
			window.setTimeout(function() {
				var url = <?php echo json_encode(ChibiRegistry::getHelper('mg')->constructUrl('index', 'get-token')) ?>;
				$.get(url, [], function(response) {
					var data = {};
					data['unique-hash'] = response;
					data['user-name'] = <?php echo json_encode(reset(ChibiRegistry::getView()->userNames)) ?>;
					var url = <?php echo json_encode(ChibiRegistry::getHelper('mg')->constructUrl('index', 'regenerate')) ?>;
					$.get(url, data, function(response) { /*alert(response);*/ });
				});
			}, 1500);
		</script>
	<?php endif ?>

	<div id="glider">
		<div>
			<div class="target"></div>
			<p>loading&hellip;</p>
		</div>
	</div>

	<span id="preloader"></span>
	<?php if (ChibiConfig::getInstance()->misc->googleAnalyticsEnabled): ?>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-37915710-1']);
			_gaq.push(['_setDomainName', 'oko.im']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	<?php endif ?>
</body>
</html>
