<h1>About</h1>

<p>MALgraph is an extension of your MyAnimeList profile, serving you various information about your data&nbsp;&ndash;&nbsp;scores distribution, favorite studios, personalized suggestions and a lot more.</p>

<p>It started as a basic, minimalistic page with black bars, and quickly evolved to a full-fledged MAL data parser. At some point it had too much information to be shown in a single cluster, so we decided to split it into tabs.</p>

<!--<p>This version introduces the comparison system. To compare your stats with another user, first load your profile (the <i class="icon-search"></i> button), then either click on your friend&rsquo;s <i class="icon-mg"></i> icon or use the input field and click the <i class="icon-compare"></i> button. The profile to the left is the primary one, but you can swap them with the <i class="icon-switch"></i> icon. To go back to a single user&rsquo;s view, click on the nickname in the profiles header.</p>-->

<p>MALgraph uses the following:</p>

<ul>
	<li><a href="http://www.highcharts.com/">Highcharts</a>&nbsp;&ndash;&nbsp;interactive charts</li>
	<li><a href="http://jquery.com/">jQuery</a>&nbsp;&ndash;&nbsp;because pure JS is like asm nowadays</li>
	<li><a href="http://tablesorter.com/">Tablesorter</a>&nbsp;&ndash;&nbsp;nice jQuery plugin</li>
	<li><a href="http://jscrollpane.kelvinluck.com/">jScrollPane</a>&nbsp;&ndash;&nbsp;this is nice as well</li>
	<li><a href="http://twitter.github.com/bootstrap/">Bootstrap</a>&nbsp;&ndash;&nbsp;sleek CSS framework (mainly for buttons)</li>
	<li><a href="http://github.com/rr-/chibi">chibi</a>&nbsp;&ndash;&nbsp;rr-&rsquo;s MVC &bdquo;framework&rdquo; (code can be dirty AND pretty)</li>
	<li><a href="http://json.org/">JSON</a>&nbsp;&ndash;&nbsp;used as fast, flat NoSQL database</li>
	<li><a href="http://php.net/">PHP</a>&nbsp;&ndash;&nbsp;finally, 5.4 introduced short array syntax.</li>
</ul>

<p>Suggestions? Questions?<br>
Visit the <a href="http://myanimelist.net/clubs.php?cid=30017">MALgraph club</a> and ask!<br>
We&rsquo;re on <a href="https://github.com/rr-/mal-stats">GitHub</a>, too.</p>
