<h1>Global statistics</h1>

<p>These graphs are based on all MALgraph users&rsquo; data. Here you can see some basic average user&rsquo;s stats: how many anime or manga they completed or how skewed their ratings are.</p>
<p>As of <?php echo date('M d Y, H:i', $this->globals->getGenerationTime()) ?> UTC we have <?php echo $this->globals->getUserCount() ?> users, <?php echo $this->globals->getAMData(AMModel::TYPE_ANIME)->getDBSize() ?> anime and <?php echo $this->globals->getAMData(AMModel::TYPE_MANGA)->getDBSize() ?> manga entries in the database.</p>

<?php foreach (AMModel::getTypes() as $am): ?>
	<div class="section <?php echo $am ?>-score-dist">
		<h2>Score distribution (<?php echo ChibiRegistry::getHelper('mg')->amText($am) ?>)</h2>
		<?php $scoreDistribution = $this->globals->getAMData($am)->getScoredistribution() ?>
		<div class="section-body">
			<ul class="infobox">
				<li>
					<div>
						<div data-tooltip="Average count of rated titles per user">
							<span class="prefix">Rated per user</span>
							<span class="subject"><?php printf('%d', floor($scoreDistribution->getRatedCount() / max(1, $this->globals->getUserCount()))) ?></span>
						</div>
					</div>
				</li>
				<li>
					<div>
						<span class="prefix">Total unrated</span>
						<span class="subject"><?php printf('%.02f', $scoreDistribution->getUnratedCount() * 100.0 / max(1, $scoreDistribution->getRatedCount() + $scoreDistribution->getUnratedCount())) ?>%</span>
					</div>
				</li>
				<li>
					<div>
						<span class="prefix">Mean score</span>
						<span class="subject"><?php printf('%.02f', $scoreDistribution->getMeanScore()) ?></span>
					</div>
				</li>
			</ul>

			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<script type="text/javascript">
				$('.<?php echo $am ?>-score-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'bar', marginRight: 35 },
						xAxis: { categories: <?php echo json_encode(array_map(function($x) { return $x == 0 ? '-' : $x; }, array_values($scoreDistribution->getGroupsKeys(Distribution::IGNORE_NULL_KEY)))) ?>, title: { text: 'Rating' } },
						yAxis: { title: { text: 'Count', margin: 15 } },
						tooltip: { formatter: function() {
							var text;
							if (this.x == '-') {
								text = 'Unrated titles: ';
							} else {
								text = 'Titles rated with ' + this.x + ': ' + this.y;
							}
							var percent = this.y * 100.0 / <?php echo max(1, $scoreDistribution->getRatedCount()) ?>;
							text += ' (' + (Math.round(percent * 100.0) / 100.0) + '%)';
							return text;
						} },
						series: [ {
							data: <?php echo json_encode(array_values($scoreDistribution->getGroupsSizes(Distribution::IGNORE_NULL_KEY))) ?>,
						} ]
					});
				});
			</script>
		</div>
	</div>
<?php endforeach ?>
