<h1>Privacy policy</h1>

<p>MALgraph downloads and stores publicly available data related to your MyAnimeList account, which is:</p>

<ul>
<li>anime and manga lists,</li>
<li>friends and clubs lists,</li>
<li>profile information (such as nickname, list views, join date, birthday, etc.)</li>
<li>activity history (episodes watched and manga read) from the last month.</li>
</ul>

<p>In addition, your anime and manga scores are used in the recommendation module, which picks a few dozen random users and bases the suggestions on anonymous scores.</p>

<p>Each refresh of your data, which happens once per 24 hours at most, will bump up your list and profile views counters by one. Although we use the API to read your lists, we make sure they’re not private by visiting them directly - if they are, their content will be hidden, but stats won’t.</p>

<p>In short, you can sleep well - we’re not evil and respect your privacy. If you still feel insecure, you can <a href="http://myanimelist.net/mymessages.php?go=send&toname=fri">ask us</a> to block your profile from being displayed here.</p>

<p>Twitter and Facebook share buttons always link back to the tab you’re currently in, so you might want to return to the profile before clicking on them.</p>
