<h1>Wrong query</h1>

<p>Your search was invalid for breaking one of following rules:</p>

<ul>
	<li>User name must contain at least 3 characters</li>
	<li>User name can contain only letters, numbers, underscores and dashes
		<ul><li>with exception to anonymous user names, which begin with &bdquo;=&rdquo;</li></ul></li>
	<li>You can combine user names to get directly to compare mode by join nicks with comma character (for example <a href="<?php echo $this->mgHelper->constructUrl('stats', null, [], ['fri', 'rr-']) ?>">&bdquo;rr-,fri&rdquo;</a>)</li>
</ul>
