<h1>Wrong query</h1>

<p>Your search was invalid for breaking one of following rules:</p>

<ul>
	<li>User name must be 2 to 16 characters long.</li>
	<li>User name can only contain letters, numbers, dashes and underscores. Anonymized names begin with &bdquo;=&rdquo;.</li>
</ul>

<p>You can combine user names to get directly to comparison mode by joining nicks with a comma, e.g. <a href="<?php echo $this->mgHelper->constructUrl('stats', null, [], ['fri', 'rr-']) ?>">rr-,fri</a>.</p>
