<h1>Serious error</h1>
<p>If you see this, please mail <a href="mailto:chrupky@gmail.com">chrupky@gmail.com</a> with information below.<br>
Also, please use "MALgraph" as the subject and include your MAL nickname. Thank you!</p>
<hr>
<p><?php echo $this->errorString ?> at <?php echo $this->errorFile ?>:<?php echo $this->errorLine ?></p>
<ul>
	<?php for ($k = 0, $i = 0; $i < count($this->backtrace); $i ++, $k ++): ?>
		<?php $b = $this->backtrace[$i]; ?>
		<li><?php
			printf
			(
				'#%d %s%s%s(%s) called at [%s:%d]',
				$k,
				@$b['class'],
				@$b['type'],
				$b['function'],
				'...', //join(', ', array_map(function($x) { return @json_encode($x); }, empty($b['args']) ? array() : $b['args'])),
				empty($b['file']) ? '[anonymous function]' : $b['file'],
				@$b['line']
			);
		?></li>
	<?php endfor ?>
</ul>
