<th class="length">
	<a class="tooltipable"
	<?php if ($this->am == UserModel::USER_LIST_TYPE_ANIME): ?>
		data-title="Length (episodes)"
	<?php else: ?>
		data-title="Length (volumes)"
	<?php endif ?>
	data-position-my="center bottom"
	data-position-at="center top"
	href="<?php echo $this->mgHelper->constructUrl(null, null, ['sort-column' => 'status', 'sort-dir' => $this->sortColumn == 'status' ? 1 - $this->sortDir : 0]) ?>">
		L
	</a>
</th>
