<div>
	<?php if (basename($this->user['profile-picture-url']) == 'na.gif'): ?>
	<?php else: ?>
		<img class="user-pic" src="<?php echo $this->user['profile-picture-url'] ?>">
	<?php endif ?>
	<div class="basic">
		<h1><?php echo $this->user['user-name'] ?></h1>
		<dl>
			<?php
				if (intval ($this->user['join-date']))
				{
					list ($year, $month, $day) = explode ('-', $this->user['join-date']);
					$time = mktime(0, 0, 0, $month, $day, $year);
					$diff = time() - $time;
					$diff /= 3600 * 24;
					echo '<dt>Time on MAL</dt>';
					echo '<dd>' . sprintf('%.1f', $diff / 361.25) . ' years</dd>';
				}
			?>

			<dt>List views</dt>
			<dd><?php echo $this->user[$this->am]['list-views'] ?></dd>

			<dt>Total clubs</dt>
			<dd><?php echo count($this->user['clubs']) ?></dd>

			<dt>Total friends</dt>
			<dd><?php echo count($this->user['friends']) ?></dd>
		</dl>

		<div class="clear"></div>
		<ul>
			<li>
				<i class="icon-pop-out"></i>
				<a href="http://myanimelist.net/profile/<?php echo $this->user['user-name'] ?>">
					MAL profile
				</a>
			</li>
			<li>
				<i class="icon-pop-out"></i>
				<a href="http://myanimelist.net/animelist/<?php echo $this->user['user-name'] ?>">
					MAL anime list
				</a>
			</li>
			<li>
				<i class="icon-pop-out"></i>
				<a href="http://myanimelist.net/mangalist/<?php echo $this->user['user-name'] ?>">
					MAL manga list
				</a>
			</li>
		</ul>
	</div>
	<div class="clear"></div>

	<p><strong>Friends:</strong></p>
	<?php if (empty($this->user['friends'])): ?>
		This user has no friends on MAL. :(
	<?php else: ?>
		<ul id="friends">
			<?php usort($this->user['friends'], function($a, $b) { return strlen($a) > strlen($b); }); ?>
			<?php foreach ($this->user['friends'] as $friend): ?>
				<li>
					<a href="<?php echo $this->urlHelper->url('/stats/index', array('user-name' => $friend)) ?>">
						<i class="icon-mg"></i>
					</a>
					<a href="http://myanimelist.net/profile/<?php echo $friend ?>">
						<?php echo $friend ?>
					</a>
				</li>
			<?php endforeach ?>
		</ul>
	<?php endif ?>

	<p><strong>Clubs:</strong></p>
	<?php if (empty($this->user['clubs'])): ?>
		<p>This user doesn't attend to any clubs.</p>
	<?php else: ?>
		<ul id="clubs">
			<?php usort($this->user['clubs'], function($a, $b) { return strlen($a['name']) > strlen($b['name']); }); ?>
			<?php foreach ($this->user['clubs'] as $club): ?>
				<li>
					<i class="icon-club"></i>
					<a href="http://myanimelist.net/clubs.php?cid=<?php echo $club['id'] ?>">
						<?php echo $club['name'] ?>
					</a>
				</li>
			<?php endforeach ?>
		</ul>
	<?php endif ?>
</div>
