<?php include 'views/_common/stats-switcher.phtml'; ?>

<div class="users">
<?php foreach ($this->users as $i => $u): ?>

	<?php if ($u['anonymous']): ?>
		<div class="user anonymous">
	<?php else: ?>
		<div class="user">
	<?php endif ?>

		<div class="section">
			<h2>
				<a href="<?php echo $this->mgHelper->url('stats/' . $this->actionName, ['u' => $u['link-name'], 'am' => $this->am]) ?>">
					<?php echo $u['visible-name'] ?>
				</a>
				`s <?php echo $this->am ?> list
			</h2>

			<div class="section-body">
				<?php if (empty($u[$this->am]['entries'])): ?>
					<p>This user doesn't seem to have anything on their list.</p>
				<?php elseif ($u[$this->am]['private']): ?>
					<p>This user has marked their list as private. No table here.</p>
				<?php else: ?>
					<div class="table">
						<table>
							<thead>
								<tr>
									<th class="ord">#</th>

									<?php include 'views/_common/stats-thead-status.phtml' ?>
									<?php include 'views/_common/stats-thead-unique.phtml' ?>
									<?php include 'views/_common/stats-thead-title.phtml' ?>
									<?php include 'views/_common/stats-thead-score.phtml' ?>
								</tr>
							</thead>

							<tbody>
								<?php $k = 1 ?>
								<?php foreach ($u[$this->am]['entries'] as $e): ?>
									<tr>
										<td class="ord"><?php echo $k ++ ?></td>
										<?php include 'views/_common/stats-tbody-status.phtml' ?>
										<?php include 'views/_common/stats-tbody-unique.phtml' ?>
										<?php include 'views/_common/stats-tbody-title.phtml' ?>
										<?php include 'views/_common/stats-tbody-score.phtml' ?>
									</tr>
								<?php endforeach ?>
							</tbody>

						</table>
					</div>
				<?php endif ?>

			</div>
		</div>

	</div>
<?php endforeach ?>
<div class="clear"></div>
</div>

<script type="text/javascript">
$('*').tooltip();
</script>
