<?php $u = $this->user ?>

<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $u['link-name']) ?>">
			<?php echo $u['visible-name'] ?>
		</a>
		`s <?php echo $this->am ?> achievements
	</h2>
</div>

<?php if (empty($u['achievements'])): ?>
	<div class="section">
		<div class="section-body">
			<p>No achievements yet! Better get to <?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'reading' : 'watching' ?>.</p>
		</div>
	</div>
<?php else: ?>
	<h2>Na pomoc fri zrub cos z wygladem</h2>
	<?php foreach ($u['achievements'] as $ach): ?>
		<?php if (!empty($ach['path'])): ?>
			<img alt="<?php echo $ach['title'] ?>" src="<?php echo $this->urlHelper->url('media/img/ach/' . $ach['path']) ?>">
		<?php endif ?>
		<div class="section">
			<h3><?php echo $ach['title'] ?></h3>
			<div class="section-body">
				<?php if (!empty($ach['level'])): ?>
					<p class="level"><?php echo $ach['level'] ?></p>
				<?php endif ?>
				<?php if (!empty($ach['desc'])): ?>
					<p class="desc"><?php echo $ach['desc'] ?></p>
				<?php endif ?>
				<?php if (!empty($ach['entries'])): ?>
					<p class="entries">Earned because you <?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'read' : 'watched' ?> these:</p>
					<ul>
						<?php foreach ($ach['entries'] as $e): ?>
							<li>
								<a href="http://myanimelist.net/<?php echo $e['full']['type'] ?>/<?php echo $e['full']['id'] ?>">
									<?php echo $e['full']['title'] ?>
								</a>
							</li>
						<?php endforeach ?>
					</ul>
				<?php endif ?>
			</div>
		</div>
	<?php endforeach ?>
<?php endif ?>
