<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user['link-name']) ?>">
			<?php echo $this->user['visible-name'] ?>
		</a>
		&rsquo;s <?php echo $this->mgHelper->amText() ?> achievements
	</h2>
</div>



<?php if (empty($this->user['achievements'])): ?>
	<div class="section">
		<div class="section-body">
			<p>No achievements yet! Better get to <?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'reading' : 'watching' ?>.</p>
		</div>
	</div>
<?php else: ?>
	<?php foreach ($this->user['achievements'] as $k => $ach): ?>
		<div class="section" data-id="<?php echo $k ?>">
		<?php if (!empty($ach['path'])): ?>
			<img class="more-trigger" alt="<?php echo $ach['title'] ?>" src="<?php echo $this->urlHelper->url('media/img/ach/' . $ach['path']) ?>">
		<?php endif ?>
			<h3>
				<?php echo $ach['title'] ?>
				<?php if (!empty($ach['level'])): ?>
					<p class="level"><?php echo $ach['level'] ?></p>
				<?php endif ?>
			</h3>
			<div class="section-body">
				<?php if (!empty($ach['desc'])): ?>
					<p class="desc"><?php echo $ach['desc'] ?></p>
				<?php endif ?>
				<?php if (!empty($ach['entries'])): ?>
					<a href="#" class="more-trigger">See related titles.</a>
					<div class="clear"></div>
					<div class="more">
						<?php if ($this->user[$this->am]['private']): ?>
							<p>This list is private.</p>
						<?php else: ?>
							<p>Earned because you <?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'read' : 'watched' ?> these:</p>
							<ul>
								<?php foreach ($ach['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $e['full']['type'] ?>/<?php echo $e['full']['id'] ?>">
											<?php echo $e['full']['title'] ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endif ?>
			</div>
		</div>
	<?php endforeach ?>
<?php endif ?>



<script type="text/javascript">
	$('#user-<?php echo $this->user['user-safe-id'] ?> .more-trigger').click(function(e) {
		var k = $(this).parents('div.section').attr('data-id');
		var target = $('#user-<?php echo $this->user['user-safe-id'] ?> .section[data-id=\'' + k + '\'] .more');
		var allTargets = $('#user-<?php echo $this->user['user-safe-id'] ?> .more');
		var isVisible = target.is(':visible');
		allTargets.slideUp('slow');
		if (!isVisible) {
			target.slideDown('slow');
		}
		e.preventDefault();
	});
</script>

<?php if ($this->isFinal): ?>
	<script type="text/javascript">
		$(function() {
			$('.section').css('height', 'auto');
		});
	</script>
<?php endif ?>
