<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section achi">
	<h2>
		<?php if (count($this->users) > 1): ?>
			<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
			&rsquo;s achievements
		<?php else: ?>
			Achievements
		<?php endif ?>
	</h2>
</div>



<?php if (empty($this->achievements[$user->getID()])): ?>
	<div class="section">
		<div class="section-body">
			<p>No achievements yet! Better get to <?php echo $this->am == AMModel::TYPE_MANGA ? 'reading' : 'watching' ?>.</p>
		</div>
	</div>
<?php else: ?>
	<?php foreach ($this->achievements[$user->getID()] as $k => $ach): ?>
		<div class="section" data-id="<?php echo $k ?>">
		<?php if (!empty($ach['path'])): ?>
			<img class="more-trigger" alt="<?php echo $ach['title'] ?>" src="<?php echo UrlHelper::url('media/img/ach/' . $ach['path']) ?>">
		<?php endif ?>
			<h3>
				<?php echo $ach['title'] ?>
				<?php if (!empty($ach['level'])): ?>
					<p class="level"><?php echo $ach['level'] ?></p>
				<?php endif ?>
			</h3>
			<div class="section-body">
				<?php if (!empty($ach['desc'])): ?>
					<p class="desc"><?php echo $ach['desc'] ?></p>
				<?php endif ?>

				<?php if (!empty($ach['entries'])): ?>
					<a href="#" class="more-trigger">See related titles.</a>

					<div class="wrapper wrapper-more">
						<p>
							<a class="close">&times;</a>
							<?php if ($user->getList($this->am)->isPrivate()): ?>
								Can&rsquo;t show you titles from a private list.</p>
							<?php else: ?>
								Earned because you
								&nbsp;<?php echo $this->am == AMModel::TYPE_MANGA ? 'read' : 'watched' ?>:
								&nbsp;(<?php echo count($ach['entries']) ?>)
							<?php endif ?>
						</p>
						<?php if (!$user->getList($this->am)->isPrivate()): ?>
							<ul>
								<?php foreach ($ach['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $e->getType() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endif ?>

				<div class="clear"></div>
			</div>
		</div>
	<?php endforeach ?>
<?php endif ?>



<script type="text/javascript">
	$('#user-<?php echo $user->getRuntimeID() ?> .more-trigger').click(function(e) {
		var k = $(this).parents('div.section').attr('data-id');
		var target = $('#user-<?php echo $user->getRuntimeID() ?> .section[data-id=\'' + k + '\'] .wrapper-more');
		toggleMoreWrappers(target, [], false);
		e.preventDefault();
	});
</script>
<?php }); ?>
