<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user['link-name']) ?>">
			<?php echo $this->user['visible-name'] ?>
		</a>
		&rsquo;s <?php echo $this->mgHelper->amText() ?> activity
	</h2>
</div>



<div class="section acti-line-daily">
	<h3>
		<i data-title="Number of titles you've completed within given day. Shows last three weeks with 24h accuracy." class="tooltipable icon-tooltip"></i>
		Activity timeline (daily)
	</h3>
	<div class="section-body">
		<ul class="infobox">
			<li>
				<div>
					<span class="prefix">Total time</span>
					<span class="subject"><?php printf('%.02f', $this->user[$this->am]['acti-info']['total-time'] / 60.0 / 24.0) ?></span>
					<span class="suffix">days</span>
				</div>
			</li>
			<li>
				<div>
					<span class="prefix">Average time</span>
					<span class="subject"><?php printf('%.02f', $this->user[$this->am]['acti-info']['mean-time']) ?></span>
					<span class="suffix">min/day</span>
				</div>
			</li>
		</ul>

		<div class="wrapper wrapper-target">
			<div class="target"></div>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->user[$this->am]['acti-info']['day-periods'] as $k => $x): ?>
				<div class="more" data-id="<?php echo $k ?>">
					<p>
						<?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'Chapters' : 'Episodes' ?>
						&nbsp;from&nbsp;
						<?php if ($k == 0): ?>
							today
						<?php elseif ($k == 1): ?>
							yesterday
						<?php else: ?>
							<?php echo $k ?> days ago
						<?php endif ?>
						<?php if (!empty($x['entries'])): ?>
							&nbsp;(<?php echo count($x['entries']) ?>)
						<?php endif ?>
						:
					</p>
					<?php if (empty($x['entries'])): ?>
						<p>None!</p>
					<?php elseif ($this->user[$this->am]['private']): ?>
						<p>Can&rsquo;t show you titles from a private list.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($x['entries'] as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
									&nbsp;&ndash;&nbsp;
									<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
										chap. <?php echo $e['user']['chap'] ?>
									<?php else: ?>
										ep. <?php echo $e['user']['ep'] ?>
									<?php endif ?>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>

		<script type="text/javascript">
			$('#user-<?php echo $this->user['user-safe-id'] ?> .acti-line-daily .target').each(function() {
				var chart = new Highcharts.Chart({
					chart: { renderTo: this, type: 'column', marginTop: 8 },
					xAxis: { categories: <?php echo json_encode(array_keys($this->user[$this->am]['acti-info']['day-periods'])) ?>, title: { text: 'Days ago', margin: 15 }, labels: { style: { fontSize: '10px !important' } } },
					yAxis: { title: { text: 'Count' }, min: 0 },
					tooltip: { formatter: function() {
						var text = '<?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'Chapters' : 'Episodes' ?> completed ';
						if (this.x == 0) {
							text += 'today';
						} else if (this.x == 1) {
							text += 'yesterday';
						} else {
							text += this.x + ' days ago';
						}
						text += ': ' + this.y;
						return text; } },
					series: [ {
						data: <?php echo json_encode(array_map(function($p) { return count($p['entries']); }, array_values($this->user[$this->am]['acti-info']['day-periods']))) ?>,
						point: { events: { click: function(e) {
							toggleWithinSections($('.acti-line-daily .more[data-id=\'' + this.x + '\']'), true);
						} } }
					} ],
					plotOptions: { column: { pointWidth: 17 } }
				});
			});
		</script>
	</div>
</div>



<div class="section acti-line-monthly">
	<h3>
		<i data-title="Number of titles you've completed within given month." class="tooltipable icon-tooltip"></i>
		Activity timeline (monthly)
	</h3>
	<div class="section-body">
		<?php if (empty($this->user[$this->view->am]['acti-info']['month-periods'])): ?>
			<p>No <?php echo $this->mgHelper->amText() ?> you've completed has its completion date specified. This graph won&rsquo;t work without this data.</p>
		<?php elseif (count($this->user[$this->view->am]['acti-info']['month-periods']) == 1): ?>
			<p>You completed <?php echo $this->mgHelper->amText() ?> from only period and that is <?php echo reset(array_keys($this->user[$this->am]['acti-info']['month-periods'])) ?>, so a graph isn&rsquo;t needed.</p>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div style="width: <?php echo count($this->user[$this->am]['acti-info']['month-periods']) * 30 + 100 ?>px" class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->user[$this->am]['acti-info']['month-periods'] as $k => $x): ?>
					<div class="more" data-id="<?php echo $k ?>">
						<p>
							<?php if ($k == '?'): ?>
								Titles with unspecified completion or start date
							<?php else: ?>
								Titles from <?php echo $k ?>
							<?php endif ?>
							<?php if (!empty($x['entries'])): ?>
								&nbsp;(<?php echo count($x['entries']) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($x['entries'])): ?>
							<p>None!</p>
						<?php elseif ($this->user[$this->am]['private']): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($x['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
											<?php echo $e['full']['title'] ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<?php
				$max = 0;
				foreach ($this->user[$this->am]['acti-info']['month-periods'] as $key => $x2) {
					if ($key != '?' and count($x2['entries']) > $max) {
						$max = count($x2['entries']);
					}
				}
				$real_max = intval(ceil($max / 5.0)) * 5;
			?>

			<script type="text/javascript">
				$('#user-<?php echo $this->user['user-safe-id'] ?> .acti-line-monthly .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'line', marginTop: 8, marginBottom: 56 },
						xAxis: { categories: <?php echo json_encode(array_keys($this->user[$this->am]['acti-info']['month-periods'])) ?>, labels: { rotation: -45, align: 'right' } },
						yAxis: { title: {text: 'Count'}, min: 0, max: <?php echo $real_max ?> },
						tooltip: { formatter: function() {
							var text = 'Titles ';
							if (this.x == '?') {
								text += 'with unspecified date: ' + this.point.real_y;
							} else {
								text += 'from ' + this.x + ': ' + this.y;
							}
							return text; } },
						series: [ {
							data:
								<?php echo json_encode(array_map(function($key) {
									$x = $this->user[$this->am]['acti-info']['month-periods'][$key];
									return count($x['entries']);
								}, array_keys($this->user[$this->am]['acti-info']['month-periods'])))
								?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.acti-line-monthly .more[data-id=\'' + this.category + '\']'), true);
							} } }
						}, {
							data: <?php
								$x = &$this->user[$this->am]['acti-info']['month-periods']['?'];
								echo json_encode([ [
									'y' => min(count($x['entries']), $real_max),
									'real_y' => count($x['entries'])
								] ] )
								?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.acti-line-monthly .more[data-id=\'' + this.category + '\']'), true);
							} } }
						}],
					});
					});
			</script>
		<?php endif ?>

	</div>
</div>



<?php if ($this->isFinal): ?>
	<script type="text/javascript">
		$(function() {
			$('.acti-line-monthly .wrapper-target').jScrollPane();
		});
	</script>
<?php endif ?>
