<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section acti-line-daily">
	<h2>
		<i data-title="Number of <?php echo $this->am == AMModel::TYPE_MANGA ? "chapters you've read" : "episodes you've watched" ?> within&nbsp;given day. Shows last 3 weeks with 24 h accuracy." class="tooltipable icon-tooltip"></i>
		<?php if (count($this->users) > 1): ?>
			<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
			&rsquo;s activity timeline (daily)
		<?php else: ?>
			Activity timeline (daily)
		<?php endif ?>
	</h2>
	<div class="section-body">
		<ul class="infobox">
			<li>
				<div>
					<span class="prefix">Total time</span>
					<span class="subject"><?php printf('%.02f', $this->actiInfo[$user->getID()]['total-time'] / 60.0 / 24.0) ?></span>
					<span class="suffix">days</span>
				</div>
			</li>
			<li>
				<div>
					<span class="prefix">Average time</span>
					<span class="subject tooltipable" data-title="Earliest time user started or finished <?php echo $this->am == AMModel::TYPE_MANGA ? 'reading' : 'watching' ?> something, or joined MAL, was&nbsp;on <?php echo date('Y-m-d', $this->actiInfo[$user->getID()]['earliest-time']) ?>"><?php printf('%.02f', $this->actiInfo[$user->getID()]['mean-time']) ?></span>
					<span class="suffix">min/day</span>
				</div>
			</li>
		</ul>

		<div class="wrapper wrapper-target">
			<div class="target"></div>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
		</div>

		<script type="text/javascript">
			$('#user-<?php echo $user->getRuntimeID() ?> .acti-line-daily .target').each(function() {
				var chart = new Highcharts.Chart({
					chart: { renderTo: this, type: 'column', marginTop: 8 },
					xAxis: { categories: <?php echo json_encode(array_keys($this->actiInfo[$user->getID()]['day-periods'])) ?>, title: { text: 'Days ago', margin: 15 }, labels: { style: { fontSize: '10px !important' } } },
					yAxis: { title: { text: '<?php echo $this->am == AMModel::TYPE_MANGA ? 'Chapter' : 'Episode' ?> count' }, min: 0 },
					tooltip: { formatter: function() {
						var text = '<?php echo $this->am == AMModel::TYPE_MANGA ? 'Chapters' : 'Episodes' ?> completed ';
						if (this.x == 0) {
							text += 'today';
						} else if (this.x == 1) {
							text += 'yesterday';
						} else {
							text += this.x + ' days ago';
						}
						text += ': ' + this.y;
						return text; } },
					series: [ {
						data: <?php echo json_encode(array_map(function($p) { return count($p); }, array_values($this->actiInfo[$user->getID()]['day-periods']))) ?>,
						point: { events: { click: function(e) {
							toggleMoreWrappers($('.acti-line-daily .wrapper-more'), {'sender': 'daily-activity', 'days-ago': this.category});
						} } }
					} ],
					plotOptions: { column: { pointWidth: 17 } }
				});
			});
		</script>
	</div>
</div>
<?php }); ?>



<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section acti-line-monthly">
	<h2>
		<i data-title="Number of titles you've completed within given month, or with no specified&nbsp;completion date." class="tooltipable icon-tooltip"></i>
		<?php if (count($this->users) > 1): ?>
			<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
			&rsquo;s activity timeline (monthly)
		<?php else: ?>
			Activity timeline (monthly)
		<?php endif ?>
	</h2>
	<div class="section-body">
		<?php if (empty($this->actiInfo[$user->getID()]['month-periods'])): ?>
			<p>No <?php echo $this->mgHelper->amText() ?> you've completed has its completion date specified.<br>
			This graph won&rsquo;t work without this data.</p>
		<?php elseif (count($this->actiInfo[$user->getID()]['month-periods']) == 1): ?>
			<?php $p = array_keys($this->actiInfo[$user->getID()]['month-periods'])[0] ?>
			<?php if ($p == '?'): ?>
				<p>No information was found about long-term completion date of your titles.</p>
			<?php else: ?>
				<p>You completed <?php echo $this->mgHelper->amText() ?> from only period and that is <?php echo array_keys($this->actiInfo[$user->getID()]['month-periods'])[0] ?>, so a graph isn&rsquo;t needed.</p>
			<?php endif ?>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div style="width: <?php echo count($this->actiInfo[$user->getID()]['month-periods']) * 30 + 100 ?>px" class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
			</div>

			<?php
				$max = 0;
				foreach ($this->actiInfo[$user->getID()]['month-periods'] as $key => $x2) {
					if ($key != '?' and count($x2['entries']) > $max) {
						$max = count($x2['entries']);
					}
				}
				$real_max = intval(ceil($max / 5.0)) * 5;
			?>

			<script type="text/javascript">
				$('#user-<?php echo $user->getRuntimeID() ?> .acti-line-monthly .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'area', marginTop: 8, marginBottom: 56 },
						xAxis: { categories: <?php echo json_encode(array_keys($this->actiInfo[$user->getID()]['month-periods'])) ?>, labels: { rotation: -45, align: 'right' } },
						yAxis: { title: {text: 'Title count'}, min: 0, max: <?php echo $real_max ?> },
						tooltip: { formatter: function() {
							var text = 'Titles ';
							if (this.x == '?') {
								text += 'with unspecified date: ' + this.point.real_y;
							} else {
								text += 'from ' + this.x + ': ' + this.y;
							}
							return text; } },
						series: [ {
							data:
								<?php echo json_encode(array_map(function($key) use ($user, $real_max) {
									$x = $this->actiInfo[$user->getID()]['month-periods'][$key];
									return [
										'y' => min(count($x['entries']), $real_max),
										'real_y' => count($x['entries'])
									];
								}, array_keys($this->actiInfo[$user->getID()]['month-periods'])))
								?>,
							point: { events: { click: function(e) {
								toggleMoreWrappers($('.acti-line-monthly .wrapper-more'), {'sender': 'monthly-activity', 'month': this.category});
							} } }
						},
						<?php if (!empty($this->actiInfo[$user->getID()]['month-periods']['?'])): ?>
							{
								data: <?php
									$x = &$this->actiInfo[$user->getID()]['month-periods']['?'];
									echo json_encode([ [
										'y' => min(count($x['entries']), $real_max),
										'real_y' => count($x['entries'])
									] ] )
									?>,
								point: { events: { click: function(e) {
									toggleMoreWrappers($('.acti-line-monthly .wrapper-more'), {'sender': 'monthly-activity', 'month': this.category});
								} } }
							}
						<?php endif ?>
						],
					});
					});
			</script>
		<?php endif ?>

	</div>
</div>
<?php }); ?>



<script type="text/javascript">
	$(function() {
		$('.acti-line-monthly .wrapper-target').jScrollPane();
	});
</script>
