<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user['link-name']) ?>">
			<?php echo $this->user['visible-name'] ?>
		</a>
		&rsquo;s <?php echo $this->mgHelper->amText() ?> favorites
	</h2>
</div>



<div class="section decades">
	<h3>
		Decades
	</h3>
	<div class="section-body">

		<div class="wrapper wrapper-target">
			<div class="target"></div>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->user[$this->am]['years'] as $k => $data): ?>
				<div class="years more" data-id="<?php echo $k ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;from&nbsp;
						<?php echo $k ?>
						:
					</p>
					<?php if (empty($data['entries'])): ?>
						<p>None!</p>
					<?php elseif ($this->user[$this->am]['private']): ?>
						<p>This list is private.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($data['entries'] as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
									&nbsp;(
									<?php if ($e['user']['score'] == 0): ?>
										unrated
									<?php else: ?>
										rated with <?php echo $e['user']['score'] ?>
									<?php endif ?>
									)
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
			<?php foreach ($this->user[$this->am]['decades'] as $k => $data): ?>
				<div class="decades more" data-id="<?php echo $k ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;from&nbsp;
						<?php echo $k ?>
						s:
					</p>
					<?php if (empty($data['entries'])): ?>
						<p>None!</p>
					<?php elseif ($this->user[$this->am]['private']): ?>
						<p>This list is private.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($data['entries'] as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
									&nbsp;(
									<?php if ($e['user']['score'] == 0): ?>
										unrated
									<?php else: ?>
										rated with <?php echo $e['user']['score'] ?>
									<?php endif ?>
									)
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>

		<script type="text/javascript">
			$('#user-<?php echo $this->user['user-safe-id'] ?> .decades .target').each(function() {
				var chart = new Highcharts.Chart({
					chart: { renderTo: this, type: 'line', marginTop: 8 },
					xAxis: { reversed: true,
						categories: <?php echo json_encode(array_keys($this->user[$this->am]['years'])) ?>,
						labels: { enabled: false },
						title: { text: 'Decades', margin: 15 },
						<?php $json = [];
							$i = 0;
							foreach ($this->user[$this->am]['decades'] as $decade) {
								if ($i ++ % 2 == 0) {
									$json []= [
										'from' => $decade['decade'] - 0.5,
										'to' => $decade['decade'] + 9.5,
										'color' => 'rgba(200, 230, 255, 0.2)',
										'label' => ['text' => $decade['decade'] . 's'],
										'zIndex' => 3,
									];
								}
							} ?>
						plotBands: <?php echo json_encode($json) ?>
					},
					yAxis: { title: { text: 'Mean' } },
					tooltip: { formatter: function() {
						var text = 'Mean score of titles from ';
						if (this.series.name == 'decades') {
							text += Math.floor(this.x / 10) * 10;
							text += 's';
						} else {
							text += this.x;
						}
						text += ': ';
						if (this.y == 0) {
							text += 'unrated!';
						} else {
							text += Math.round(this.y * 100) / 100.0;
						}
						return text; } },
					series: [ {
						name: 'years',
						data: <?php echo json_encode(array_map(function($data) { return [$data['year'], $data['mean-score']]; }, array_values($this->user[$this->am]['years']))) ?>,
						point: { events: { click: function(e) {
							toggleWithinSections($('.decades .years.more[data-id=\'' + this.category + '\']'), true);
						} } }
					}, {
						name: 'decades',
						data: <?php echo json_encode(array_map(function($data) { return [$data['decade'] + 4.5, $data['mean-score']]; }, array_values($this->user[$this->am]['decades']))) ?>,
						point: { events: { click: function(e) {
							var decade = Math.floor(this.category / 10) * 10;
							toggleWithinSections($('.decades .decades.more[data-id=\'' + decade + '\']'), true);
						} } }
					} ],
					plotOptions: { column: { pointWidth: 17 } }
				});
			});
		</script>
	</div>
</div>



<div class="section producers">
	<h3>
		<i data-title="List of producers this user might like." class="tooltipable icon-tooltip"></i>
		Producers
	</h3>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if (empty($this->user[$this->am]['producers'])): ?>
				<p>Looks like there are no known producers for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Title</th>
							<th class="count tooltipable" data-title="Count of titles from this studio user has on their list">Count</th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->user[$this->am]['producers'] as $producer): ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a
									<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
										href="http://myanimelist.net/people/<?php echo $producer['id'] ?>/"
									<?php else: ?>
										href="http://myanimelist.net/anime.php?p=<?php echo $producer['id'] ?>"
									<?php endif ?>
								>
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $producer['id'] ?>" href="#">
									<?php echo htmlspecialchars($producer['name']) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($producer['entries'])) ?></td>
							<td class="mean">
								<?php if ($producer['mean-score'] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $producer['mean-score']) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $producer['total-time'] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->user[$this->am]['producers'] as $producer): ?>
				<div class="more" data-id="<?php echo $producer['id'] ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;from&nbsp;
						<?php echo $producer['name'] ?>
						&nbsp;(<?php echo count($producer['entries']) ?>):
					</p>
					<?php if (empty($producer['entries'])): ?>
						<p>None!</p>
					<?php elseif ($this->user[$this->am]['private']): ?>
						<p>This list is private.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($producer['entries'] as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
									&nbsp;<span class="info">(
										<?php if ($e['user']['score'] == 0): ?>
											unknown&nbsp;rating&nbsp;&ndash; assumed&nbsp;mean
										<?php else: ?>
											rated&nbsp;with&nbsp;<?php echo $e['user']['score'] ?>
										<?php endif ?>
									, <?php echo $e['user']['total-time'] ?>&nbsp;min.)</span>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>
	</div>
</div>



<div class="section genres">
	<h3>
		<i data-title="List of genres this user might like." class="tooltipable icon-tooltip"></i>
		Genres
	</h3>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if (empty($this->user[$this->am]['genres'])): ?>
				<p>Looks like there are no known genres for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Title</th>
							<th class="count"><span class="tooltipable" data-title="Count of titles from this genre user has on their list">Count</span></th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->user[$this->am]['genres'] as $genre): ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>.php?genre[]=<?php echo $genre['id'] ?>">
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $genre['id'] ?>" href="#">
									<?php echo htmlspecialchars(ucfirst($genre['name'])) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($genre['entries'])) ?></td>
							<td class="mean">
								<?php if ($genre['mean-score'] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $genre['mean-score']) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $genre['total-time'] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->user[$this->am]['genres'] as $genre): ?>
				<div class="more" data-id="<?php echo $genre['id'] ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;from&nbsp;
						<?php echo $genre['name'] ?>
						&nbsp;(<?php echo count($genre['entries']) ?>):
					</p>
					<?php if (empty($genre['entries'])): ?>
						<p>None!</p>
					<?php elseif ($this->user[$this->am]['private']): ?>
						<p>This list is private.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($genre['entries'] as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
									&nbsp;<span class="info">(
										<?php if ($e['user']['score'] == 0): ?>
											unknown&nbsp;rating&nbsp;&ndash; assumed&nbsp;mean
										<?php else: ?>
											rated&nbsp;with&nbsp;<?php echo $e['user']['score'] ?>
										<?php endif ?>
									, <?php echo $e['user']['total-time'] ?>&nbsp;min.)</span>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>
	</div>
</div>



<script type="text/javascript">
	$('#user-<?php echo $this->user['user-safe-id'] ?> .more-trigger').click(function(e) {
		e.preventDefault();
		var k = $(this).attr('data-id');
		var target = $(this).parents('.section').find('.more[data-id=\'' + k + '\']');
		toggleWithinSections(target, true);
	});
</script>

<?php if ($this->isFinal): ?>
	<script type="text/javascript">
		$(function() {
			$.tablesorter.addWidget({
				id: 'ord',
				format: function(table) {
					for (var i = 0; i < table.tBodies[0].rows.length; i ++) {
						$('tbody tr:eq(' + i + ') td:first', table).text(i + 1);
					}
				}
			});

			$('table').tablesorter({
				headers: { 0: { sorter: false }, 4: { sorter: 'percent' } },
				widgets: ['ord'],
				sortList: [[2,1],[3,1]]
			});
		});
	</script>
<?php endif ?>
