<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section decades">
	<h2>
		<i data-title="Shows your mean score of titles from&nbsp;any year or decade." class="tooltipable icon-tooltip"></i>
		<?php if (count($this->users) > 1): ?>
			<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
			&rsquo;s favorite decades
		<?php else: ?>
			Favorite decades
		<?php endif ?>
	</h2>
	<div class="section-body">

		<?php if ($this->favYears[$user->getID()]->getLargestGroupSize() == 0): ?>
			<p>There is no information about any completion dates for this user.</p>
			<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $user->getRuntimeID() ?> .decades .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'line', marginTop: 8 },
						xAxis: {
							categories: <?php echo json_encode(array_reverse($this->favYears[$user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY))) ?>,
							labels: { enabled: false },
							title: { text: 'Decades', margin: 15 },
							<?php $json = [];
								$i = 0;
								foreach ($this->favDecades[$user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY) as $decade) {
									if ($i ++ % 2 == 0) {
										$json []= [
											'from' => $decade - 0.5,
											'to' => $decade + 9.5,
											'color' => 'rgba(200, 230, 255, 0.2)',
											'label' => ['text' => $decade . 's'],
											'zIndex' => 3,
										];
									}
								} ?>
							plotBands: <?php echo json_encode($json) ?>
						},
						yAxis: { title: { text: 'Mean score' } },
						tooltip: { formatter: function() {
							var text = 'Mean score of titles from ';
							if (this.series.name == 'decades') {
								text += Math.floor(this.x / 10) * 10;
								text += 's';
							} else {
								text += this.x;
							}
							text += ': ';
							if (this.y == 0) {
								text += 'unrated!';
							} else {
								text += Math.round(this.y * 100) / 100.0;
							}
							return text; } },
						series: [ {
							name: 'years',
							data: <?php echo json_encode(array_reverse(array_map(function($year) use ($user) {
								return [$year, $this->yearScores[$user->getID()][$year]];
							}, $this->favYears[$user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY)))) ?>,
							point: { events: { click: function(e) {
								toggleMoreWrappers($('.decades .wrapper-more'), {'sender': 'year', 'year': this.category});
							} } }
						}, {
							name: 'decades',
							data: <?php echo json_encode(array_reverse(array_map(function($decade) use ($user) {
								return [$decade + 4.5, $this->decadeScores[$user->getID()][$decade]]; },
							$this->favDecades[$user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY)))) ?>,
							point: { events: { click: function(e) {
								toggleMoreWrappers($('.decades .wrapper-more'), {'sender': 'decade', 'decade': Math.floor(this.category / 10) * 10});
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>
<?php }); ?>



<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section creators">
	<h2>
		<?php if ($this->am == AMModel::TYPE_MANGA): ?>
			<i data-title="People that chose drawing over sleeping. Sorted by number of titles on your list." class="tooltipable icon-tooltip"></i>
			<?php if (count($this->users) > 1): ?>
				<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
					<?php echo $user->getPublicName() ?>
				</a>
				&rsquo;s favorite authors
			<?php else: ?>
				Favorite authors
			<?php endif ?>
		<?php elseif ($this->am == AMModel::TYPE_ANIME): ?>
			<i data-title="Anime studios that made your cartoons. Sorted by number of titles on your list." class="tooltipable icon-tooltip"></i>
			<?php if (count($this->users) > 1): ?>
				<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
					<?php echo $user->getPublicName() ?>
				</a>
				&rsquo;s favorite studios
			<?php else: ?>
				Favorite studios
			<?php endif ?>
		<?php else: ?>
			<?php continue ?>
		<?php endif ?>
	</h2>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if ($this->favCreators[$user->getID()]->getLargestGroupSize() == 0): ?>
				<p>Looks like there are no known creators for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count tooltipable" data-title="Count of titles from this creator.">Count</th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->favCreators[$user->getID()]->getGroupsKeys() as $creator): ?>
						<?php $entries = $this->favCreators[$user->getID()]->getGroupEntries($creator) ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a
									<?php if ($this->am == AMModel::TYPE_MANGA): ?>
										href="http://myanimelist.net/people/<?php echo $creator->getID() ?>/"
									<?php else: ?>
										href="http://myanimelist.net/anime.php?p=<?php echo $creator->getID() ?>"
									<?php endif ?>
								>
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $creator->getID() ?>" href="#">
									<?php echo htmlspecialchars($creator->getName()) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($entries)) ?></td>
							<td class="mean">
								<?php if ($this->creatorScores[$user->getID()][$creator->getID()] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $this->creatorScores[$user->getID()][$creator->getID()]) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $this->creatorTimeSpent[$user->getID()][$creator->getID()] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
		</div>
	</div>
</div>

<script type="text/javascript">
	$('#user-<?php echo $user->getRuntimeID() ?> .creators .more-trigger').click(function(e) {
		e.preventDefault();
		toggleMoreWrappers($('.creators .wrapper-more'), {'sender': 'creator', 'creator': $(this).attr('data-id')});
	});
</script>
<?php }); ?>



<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section genres">
	<h2>
		<i data-title="Top genres and demographics, sorted&nbsp;by&nbsp;count on your <?php echo $this->mgHelper->amText() ?> list." class="tooltipable icon-tooltip"></i>
		<?php if (count($this->users) > 1): ?>
			<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
			&rsquo;s favorite genres
		<?php else: ?>
			Favorite genres
		<?php endif ?>
	</h2>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if ($this->favGenres[$user->getID()]->getLargestGroupSize() == 0): ?>
				<p>Looks like there are no known genres for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count"><span class="tooltipable" data-title="Count of titles from this genre.">Count</span></th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->favGenres[$user->getID()]->getGroupsKeys() as $genre): ?>
						<?php $entries = $this->favGenres[$user->getID()]->getGroupEntries($genre) ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>.php?genre[]=<?php echo $genre->getID() ?>">
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $genre->getID() ?>" href="#">
									<?php echo htmlspecialchars(ucfirst($genre->getName())) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($entries)) ?></td>
							<td class="mean">
								<?php if ($this->genreScores[$user->getID()][$genre->getID()] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $this->genreScores[$user->getID()][$genre->getID()]) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $this->genreTimeSpent[$user->getID()][$genre->getID()] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
		</div>
	</div>
</div>

<script type="text/javascript">
	$('#user-<?php echo $user->getRuntimeID() ?> .genres .more-trigger').click(function(e) {
		e.preventDefault();
		toggleMoreWrappers($('.genres .wrapper-more'), {'sender': 'genre', 'genre': $(this).attr('data-id')});
	});
</script>
<?php }); ?>



<script type="text/javascript">
	$(function() {
		$.tablesorter.addWidget({
			id: 'ord',
			format: function(table) {
				for (var i = 0; i < table.tBodies[0].rows.length; i ++) {
					$('tbody tr:eq(' + i + ') td:first', table).text(i + 1);
				}
			}
		});

		$('table').tablesorter({
			headers: { 0: { sorter: false }, 4: { sorter: 'percent' } },
			widgets: ['ord'],
			sortList: [[2,1],[3,1]]
		});
	});
</script>
