<?php /**/ ?>
<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user->getLinkableName()) ?>">
			<?php echo $this->user->getPublicName() ?>
		</a>
		&rsquo;s <?php echo $this->mgHelper->amText() ?> favorites
	</h2>
</div>



<div class="section decades">
	<h3>
		<i data-title="Shows your mean score of titles from any year or decade." class="tooltipable icon-tooltip"></i>
		Decades
	</h3>
	<div class="section-body">

		<?php if ($this->favYears[$this->user->getID()]->getLargestGroupSize() == 0): ?>
			<p>There is no information about any completion dates for this user.</p>
			<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->favYears[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY) as $year): ?>
					<?php $entries = $this->favYears[$this->user->getID()]->getGroupEntries($year) ?>
					<div class="years more" data-id="<?php echo $year ?>">
						<p>
							<?php echo ucfirst($this->mgHelper->amText()) ?>
							&nbsp;from&nbsp;
							<?php echo $year ?>
							<?php if (!empty($entries)): ?>
								&nbsp;(<?php echo count($entries) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($entries)): ?>
							<p>None!</p>
						<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($entries as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
										&nbsp;(
										<?php if ($e->getScore() == 0): ?>
											unrated
										<?php else: ?>
											rated with <?php echo $e->getScore() ?>
										<?php endif ?>
										)
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
				<?php foreach ($this->favDecades[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY) as $decade): ?>
					<?php $entries = $this->favDecades[$this->user->getID()]->getGroupEntries($decade) ?>
					<div class="decades more" data-id="<?php echo $decade ?>">
						<p>
							<?php echo ucfirst($this->mgHelper->amText()) ?>
							&nbsp;from&nbsp;
							<?php echo $decade ?>
							s
							<?php if (!empty($entries)): ?>
								&nbsp;(<?php echo count($entries) ?>)
							<?php endif ?>:
						</p>
						<?php if (empty($entries)): ?>
							<p>None!</p>
						<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($entries as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
										&nbsp;(
										<?php if ($e->getScore() == 0): ?>
											unrated
										<?php else: ?>
											rated with <?php echo $e->getScore() ?>
										<?php endif ?>
										)
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user->getRuntimeID() ?> .decades .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'line', marginTop: 8 },
						xAxis: {
							categories: <?php echo json_encode($this->favYears[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY)) ?>,
							labels: { enabled: false },
							title: { text: 'Decades', margin: 15 },
							<?php $json = [];
								$i = 0;
								foreach ($this->favDecades[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY) as $decade) {
									if ($i ++ % 2 == 0) {
										$json []= [
											'from' => $decade - 0.5,
											'to' => $decade + 9.5,
											'color' => 'rgba(200, 230, 255, 0.2)',
											'label' => ['text' => $decade . 's'],
											'zIndex' => 3,
										];
									}
								} ?>
							plotBands: <?php echo json_encode($json) ?>
						},
						yAxis: { title: { text: 'Mean' } },
						tooltip: { formatter: function() {
							var text = 'Mean score of titles from ';
							if (this.series.name == 'decades') {
								text += Math.floor(this.x / 10) * 10;
								text += 's';
							} else {
								text += this.x;
							}
							text += ': ';
							if (this.y == 0) {
								text += 'unrated!';
							} else {
								text += Math.round(this.y * 100) / 100.0;
							}
							return text; } },
						series: [ {
							name: 'years',
							data: <?php echo json_encode(array_map(function($year) { return [$year, $this->yearScores[$this->user->getID()][$year]]; }, $this->favYears[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY))) ?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.decades .years.more[data-id=\'' + this.category + '\']'), true);
							} } }
						}, {
							name: 'decades',
							data: <?php echo json_encode(array_map(function($decade) { return [$decade + 4.5, $this->decadeScores[$this->user->getID()][$decade]]; }, $this->favDecades[$this->user->getID()]->getGroupsKeys(Distribution::IGNORE_NULL_KEY))) ?>,
							point: { events: { click: function(e) {
								var decade = Math.floor(this.category / 10) * 10;
								toggleWithinSections($('.decades .decades.more[data-id=\'' + decade + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>



<div class="section creators">
	<h3>
		<?php if ($this->am == AMModel::TYPE_MANGA): ?>
			<i data-title="Manga authors sorted by number of titles on your list." class="tooltipable icon-tooltip"></i>
			Authors
		<?php elseif ($this->am == AMModel::TYPE_ANIME): ?>
			<i data-title="Anime studios sorted by number of titles on your list." class="tooltipable icon-tooltip"></i>
			Studios
		<?php else: ?>
			<?php continue ?>
		<?php endif ?>
	</h3>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if ($this->favCreators[$this->user->getID()]->getLargestGroupSize() == 0): ?>
				<p>Looks like there are no known creators for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count tooltipable" data-title="Count of titles from this studio user has on their list">Count</th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->favCreators[$this->user->getID()]->getGroupsKeys() as $creator): ?>
						<?php $entries = $this->favCreators[$this->user->getID()]->getGroupEntries($creator) ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a
									<?php if ($this->am == AMModel::TYPE_MANGA): ?>
										href="http://myanimelist.net/people/<?php echo $creator->getID() ?>/"
									<?php else: ?>
										href="http://myanimelist.net/anime.php?p=<?php echo $creator->getID() ?>"
									<?php endif ?>
								>
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $creator->getID() ?>" href="#">
									<?php echo htmlspecialchars($creator->getName()) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($entries)) ?></td>
							<td class="mean">
								<?php if ($this->creatorScores[$this->user->getID()][$creator->getID()] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $this->creatorScores[$this->user->getID()][$creator->getID()]) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $this->creatorTimeSpent[$this->user->getID()][$creator->getID()] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->favCreators[$this->user->getID()]->getGroupsKeys() as $creator): ?>
				<?php $entries = $this->favCreators[$this->user->getID()]->getGroupEntries($creator) ?>
				<div class="more" data-id="<?php echo $creator->getID() ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;from&nbsp;
						<?php echo $creator->getName() ?>
						<?php if (!empty($entries)): ?>
							&nbsp;(<?php echo count($entries) ?>)
						<?php endif ?>
						:
					</p>
					<?php if (empty($entries)): ?>
						<p>None!</p>
					<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
						<p>Can&rsquo;t show you titles from a private list.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($entries as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
										<?php echo $e->getAMEntry()->getTitle() ?>
									</a>
									&nbsp;<span class="info">(
										<?php if ($e->getScore() == 0): ?>
											unknown&nbsp;rating&nbsp;&ndash; assumed&nbsp;mean
										<?php else: ?>
											rated&nbsp;with&nbsp;<?php echo $e->getScore() ?>
										<?php endif ?>
									, <?php echo $e->getCompletedDuration() ?>&nbsp;min.)</span>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
			<div class="more" data-id="null"></div>
		</div>
	</div>
</div>



<div class="section genres">
	<h3>
		<i data-title="Top genres and demographics, sorted by count on your <?php echo $this->mgHelper->amText() ?> list." class="tooltipable icon-tooltip"></i>
		Genres
	</h3>
	<div class="section-body">
		<div class="wrapper scrollable">

			<?php if ($this->favGenres[$this->user->getID()]->getLargestGroupSize() == 0): ?>
				<p>Looks like there are no known genres for this user.</p>
				<p>Add a few titles and come back in 24 hours.<br>We'll be waiting for you.</p>
			<?php else: ?>
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count"><span class="tooltipable" data-title="Count of titles from this genre user has on their list">Count</span></th>
							<th class="mean">Mean</th>
							<th class="time">Hours</th>
						</tr>
					</thead>
					<tbody>
					<?php $i = 1 ?>
					<?php foreach ($this->favGenres[$this->user->getID()]->getGroupsKeys() as $genre): ?>
						<?php $entries = $this->favGenres[$this->user->getID()]->getGroupEntries($genre) ?>
						<tr>
							<td class="ord"><?php echo $i ++ ?></td>
							<td class="title">
								<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>.php?genre[]=<?php echo $genre->getID() ?>">
									<i class="icon-pop-out"></i>
								</a>
								&nbsp;
								<a class="more-trigger" data-id="<?php echo $genre->getID() ?>" href="#">
									<?php echo htmlspecialchars(ucfirst($genre->getName())) ?>
								</a>
							</td>
							<td class="count"><?php printf('%d', count($entries)) ?></td>
							<td class="mean">
								<?php if ($this->genreScores[$this->user->getID()][$genre->getID()] == 0): ?>
									-
								<?php else: ?>
									<?php printf('%.02f', $this->genreScores[$this->user->getID()][$genre->getID()]) ?>
								<?php endif ?>
							</td>
							<td class="time"><?php printf('%.02f', $this->genreTimeSpent[$this->user->getID()][$genre->getID()] / 60.0) ?>h</td>
						</tr>
					<?php endforeach ?>
				</table>
			<?php endif ?>
			<div class="clear"></div>
		</div>

		<div class="wrapper wrapper-more">
			<?php foreach ($this->favGenres[$this->user->getID()]->getGroupsKeys() as $genre): ?>
				<?php $entries = $this->favGenres[$this->user->getID()]->getGroupEntries($genre) ?>
				<div class="more" data-id="<?php echo $genre->getID() ?>">
					<p>
						<?php echo ucfirst($this->mgHelper->amText()) ?>
						&nbsp;tagged as&nbsp;
						<?php echo ucfirst($genre->getName()) ?>
						<?php if (!empty($entries)): ?>
							&nbsp;(<?php echo count($entries) ?>)
						<?php endif ?>
						:
					</p>
					<?php if (empty($entries)): ?>
						<p>None!</p>
					<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
						<p>Can&rsquo;t show you titles from a private list.</p>
					<?php else: ?>
						<ul>
							<?php foreach ($entries as $e): ?>
								<li>
									<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
										<?php echo $e->getAMEntry()->getTitle() ?>
									</a>
									&nbsp;<span class="info">(
										<?php if ($e->getScore() == 0): ?>
											unknown&nbsp;rating&nbsp;&ndash; assumed&nbsp;mean
										<?php else: ?>
											rated&nbsp;with&nbsp;<?php echo $e->getScore() ?>
										<?php endif ?>
									, <?php echo $e->getCompletedDuration() ?>&nbsp;min.)</span>
								</li>
							<?php endforeach ?>
						</ul>
					<?php endif ?>
				</div>
			<?php endforeach ?>
			<div class="more" data-id="null"></div>
		</div>
	</div>
</div>



<script type="text/javascript">
	$('#user-<?php echo $this->user->getRuntimeID() ?> .more-trigger').click(function(e) {
		e.preventDefault();
		var k = $(this).attr('data-id');
		var selBase = '.' + $(this).parents('.section').attr('class').replace(/\s+/g, '.');
		var selFinal = [];
		$(selBase).each(function() {
			var selSubBase = '#' + $(this).parents('.user').attr('id') + ' ' + selBase;
			var sel1 = selSubBase + ' .more[data-id=\'' + k + '\']';
			var sel2 = selSubBase + ' .more[data-id=\'null\']';
			var target = $(sel1);
			if (!target.length) {
				selFinal.push(sel2);
			} else {
				selFinal.push(sel1);
			}
		});
		selFinal = selFinal.join(',');
		console.log(selFinal);
		toggleWithinSections($(selFinal), true);
	});
</script>

<?php if ($this->isFinal): ?>
	<script type="text/javascript">
		$(function() {
			$.tablesorter.addWidget({
				id: 'ord',
				format: function(table) {
					for (var i = 0; i < table.tBodies[0].rows.length; i ++) {
						$('tbody tr:eq(' + i + ') td:first', table).text(i + 1);
					}
				}
			});

			$('table').tablesorter({
				headers: { 0: { sorter: false }, 4: { sorter: 'percent' } },
				widgets: ['ord'],
				sortList: [[2,1],[3,1]]
			});
		});
	</script>
<?php endif ?>
<?php /**/ ?>
