<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user['link-name']) ?>">
			<?php echo $this->user['visible-name'] ?>
		</a>
		`s <?php echo $this->mgHelper->amText() ?> list
	</h2>

	<div class="section-body">
		<?php if (empty($this->user[$this->am]['entries'])): ?>
			<p>This user doesn't seem to have anything on their list.</p>
		<?php elseif ($this->user[$this->am]['private']): ?>
			<p>This user has marked their list as private. No table here.</p>
		<?php else: ?>
			<div class="table">
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="status">
								<span class="tooltipable"
									data-title="Status"
									data-position-my="center bottom"
									data-position-at="center top"
								>
									S
								</span>
							</th>

							<?php if (count($this->view->users) > 1): ?>
								<th class="unique">
									<span class="tooltipable"
										data-title="Unique - marked with &bdquo;+&rdquo; if only this user has given title in their list."
										data-position-my="center bottom"
										data-position-at="center top"
									>
										U
									</span>
								</th>
							<?php endif ?>

							<th class="title">
								Title
							</th>

							<th class="score">
								Score
							</th>
						</tr>
					</thead>

					<tbody>
						<?php $k = 1 ?>
						<?php foreach ($this->user[$this->am]['entries'] as $e): ?>
							<?php if ($e['user']['unique']): ?>
								<tr class="unique">
							<?php else: ?>
								<tr>
							<?php endif ?>

								<?php if ($e['user']['status'] == UserModel::USER_LIST_STATUS_PLANNED): ?>
									<td class="status" data-sorter="4">
										<i data-title="Planned" class="icon-schedule tooltipable"></i>
								<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_DROPPED): ?>
									<td class="status" data-sorter="5">
										<i data-title="Dropped" class="icon-cross tooltipable"></i>
								<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_WATCHING): ?>
									<td class="status" data-sorter="1">
										<i data-title="Watching" class="icon-eye tooltipable"></i>
								<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_ONHOLD): ?>
									<td class="status" data-sorter="3">
										<i data-title="On-hold" class="icon-hourglass tooltipable"></i>
								<?php elseif ($e['user']['status'] == UserModel::USER_LIST_STATUS_COMPLETED): ?>
									<td class="status" data-sorter="2">
										<i data-title="Completed" class="icon-tick tooltipable"></i>
								<?php endif ?>
								</td>

								<?php if (count($this->view->users) > 1): ?>
									<?php if ($e['user']['unique']): ?>
										<td class="unique" data-sorter="1">
											<i data-title="Only this user has this title on his list" class="tooltipable icon-plus"></i>
									<?php else: ?>
										<td class="unique" data-sorter="0">
											<i data-title="Both users have this title on their lists" class="tooltipable icon-dot"></i>
									<?php endif ?>
									</td>
								<?php endif ?>

								<td class="title" data-sorter="<?php echo $e['full']['title'] ?>">
									<a href="http://myanimelist.net/<?php echo $this->view->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
										<?php echo $e['full']['title'] ?>
									</a>
								</td>

								<?php if (!empty($e['others']) and count($e['others']) == 1): ?>
									<?php $e2 = reset($e['others']) ?>
									<?php if ($e['user']['score'] > $e2['user']['score']): ?>
										<?php if ($e2['user']['score'] > 0): ?>
											<td class="score higher-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="This title was rated lower (<?php echo $e2['user']['score'] ?>) by the other user.">
										<?php else: ?>
											<td class="score no-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="This title wasn't rated by the other user.">
										<?php endif ?>
									<?php elseif ($e['user']['score'] < $e2['user']['score']): ?>
										<?php if ($e['user']['score'] > 0): ?>
											<td class="score lower-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="This title was rated higher (<?php echo $e2['user']['score'] ?>) by the other user.">
										<?php else: ?>
											<td class="score no-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="This title wasn't rated by this user.">
										<?php endif ?>
									<?php else: ?>
										<?php if ($e['user']['score'] > 0): ?>
											<td class="score same-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="Both users rated this title equally.">
										<?php else: ?>
											<td class="score no-score" data-sorter="<?php echo $e['user']['score'] ?>">
												<span class="tooltipable" data-title="None of users rated this title.">
										<?php endif ?>
									<?php endif ?>
								<?php else: ?>
									<td class="score" data-sorter="<?php echo $e['user']['score'] ?>">
										<span>
								<?php endif ?>
									<?php if (empty($e['user']['score'])): ?>
										-
									<?php else: ?>
										<?php echo $e['user']['score'] ?>
									<?php endif ?>
									</span>
								</td>
							</tr>
						<?php endforeach ?>
					</tbody>

				</table>
			</div>
		<?php endif ?>

	</div>
</div>

<?php if ($this->user == reset($this->users)): ?>
	<script type="text/javascript">
		$(function() {
			$('table').tablesorter({
				textExtraction: function(node) {
					return $(node).attr('data-sorter');
				},
				<?php if (count($this->sers) > 1): ?>
					sortList: [[3,1],[2,0]]
				<?php else: ?>
					sortList: [[2,1],[1,0]]
				<?php endif ?>
			});
		});
	</script>
<?php endif ?>
