<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user->getLinkableName()) ?>">
			<?php echo $this->user->getPublicName() ?>
		</a>
		&rsquo;s <?php echo $this->mgHelper->amText() ?> list
	</h2>

	<div class="section-body">
		<?php if (count($this->user->getList($this->am)->getEntries()) == 0): ?>
			<p>Sadly, <?php echo $this->user['visible-name'] ?>&rsquo;s <?php echo $this->mgHelper->amText() ?> list is empty.<br>
			If this is your list, add (and rate) something and come back in 24 hours.</p>
		<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
			<p><?php echo ucfirst($this->mgHelper->amText()) ?> list of this user is private.<br>Each of us has some dirty secrets, isn&rsquo;t that right?</p>
		<?php else: ?>
			<div class="table">
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="status tooltipable"
								data-title="Status"
								data-position-my="center bottom"
								data-position-at="center top"
							>
								S
							</th>

							<?php if (count($this->users) > 1): ?>
								<th class="unique tooltipable"
									data-title="Unique - marked with &bdquo;+&rdquo; if only this user has given title in their list."
									data-position-my="center bottom"
									data-position-at="center top"
								>
									U
								</th>
							<?php endif ?>

							<th class="title">
								Title
							</th>

							<th class="score">
								Score
							</th>
						</tr>
					</thead>

					<?php ChibiRegistry::getHelper('benchmark')->benchmark('tbody') ?>

					<tbody>
						<?php $k = 1 ?>
						<?php foreach ($this->user->getList($this->am)->getEntries() as $e): ?>
							<?php $e2 = null ?>
							<?php if (!empty($this->otherUser)): ?>
								<?php $e2 = $this->otherUser->getList($this->am)->getEntryByID($e->getID()) ?>
							<?php endif ?>
							<?php if (empty($e2)): ?>
								<tr class="unique">
							<?php else: ?>
								<tr>
							<?php endif ?>
								<?php switch($e->getStatus()) {
									case UserListEntry::STATUS_PLANNED: ?>
									<td class="status tooltipable" data-title="<?php echo $this->mgHelper->statusText($e->getStatus()) ?>" data-sorter="4">
										<i class="icon-schedule"></i>
								<?php break; case UserListEntry::STATUS_DROPPED: ?>
									<td class="status tooltipable" data-title="<?php echo $this->mgHelper->statusText($e->getStatus()) ?>" data-sorter="5">
										<i class="icon-cross"></i>
								<?php break; case UserListEntry::STATUS_WATCHING: ?>
									<td class="status tooltipable" data-title="<?php echo $this->mgHelper->statusText($e->getStatus()) ?>" data-sorter="1">
										<i class="icon-eye"></i>
								<?php break; case UserListEntry::STATUS_ONHOLD: ?>
									<td class="status tooltipable" data-title="<?php echo $this->mgHelper->statusText($e->getStatus()) ?>" data-sorter="3">
										<i class="icon-hourglass"></i>
								<?php break; case UserListEntry::STATUS_COMPLETED: ?>
									<td class="status tooltipable" data-title="<?php echo $this->mgHelper->statusText($e->getStatus()) ?>" data-sorter="2">
										<i class="icon-tick"></i>
								<?php break; } ?>
								</td>

								<?php if (count(ChibiRegistry::getView()->users) > 1): ?>
									<?php if (empty($e2)): ?>
										<td class="unique tooltipable" data-title="Only this user has this title on his list" data-sorter="1">
											<i class="icon-plus"></i>
									<?php else: ?>
										<td class="unique tooltipable" data-title="Both users have this title on their lists" data-sorter="0">
											<i class="icon-dot"></i>
									<?php endif ?>
									</td>
								<?php endif ?>

								<td class="title" data-sorter="<?php echo $e->getAMEntry()->getTitle() ?>">
									<a href="http://myanimelist.net/<?php echo ChibiRegistry::getHelper('mg')->amText() ?>/<?php echo $e->getID() ?>">
										<?php echo $e->getAMEntry()->getTitle() ?>
									</a>
								</td>

								<?php if (!empty($e2)): ?>
									<?php if ($e->getScore() > $e2->getScore()): ?>
										<?php if ($e2->getScore() > 0): ?>
											<td class="score higher-score tooltipable" data-title="This title was rated lower (<?php echo $e2->getScore() ?>) by the other user." data-sorter="<?php echo $e->getScore() ?>">
										<?php else: ?>
											<td class="score no-score tooltipable" data-title="This title wasn&rsquo;t rated by the other user." data-sorter="<?php echo $e->getScore() ?>">
										<?php endif ?>
									<?php elseif ($e->getScore() < $e2->getScore()): ?>
										<?php if ($e->getScore() > 0): ?>
											<td class="score lower-score tooltipable" data-title="This title was rated higher (<?php echo $e2->getScore() ?>) by the other user." data-sorter="<?php echo $e->getScore() ?>">
										<?php else: ?>
											<td class="score no-score tooltipable" data-title="This title wasn&rsquo;t rated by this user." data-sorter="<?php echo $e->getScore() ?>">
										<?php endif ?>
									<?php else: ?>
										<?php if ($e->getScore() > 0): ?>
											<td class="score same-score tooltipable" data-title="Both users rated this title equally." data-sorter="<?php echo $e->getScore() ?>">
										<?php else: ?>
											<td class="score no-score tooltipable" data-title="None of users rated this title." data-sorter="<?php echo $e->getScore() ?>">
										<?php endif ?>
									<?php endif ?>
								<?php else: ?>
									<?php if (count($this->users) > 1): ?>
										<td class="score tooltipable" data-title="This title is unique to this user." data-sorter="<?php echo $e->getScore() ?>">
									<?php else: ?>
										<td class="score" data-sorter="<?php echo $e->getScore() ?>">
									<?php endif ?>
								<?php endif ?>
									<?php if (!$e->getScore()): ?>
										-
									<?php else: ?>
										<?php echo $e->getScore() ?>
									<?php endif ?>
								</td>
							</tr>
						<?php endforeach ?>
					</tbody>

					<?php ChibiRegistry::getHelper('benchmark')->benchmark('/tbody') ?>
				</table>
			</div>
		<?php endif ?>

	</div>
</div>



<?php if ($this->isFinal): ?>
	<script type="text/javascript">
		$(function() {
			$('table').tablesorter({
				textExtraction: function(node) {
					return $(node).attr('data-sorter');
				},
				<?php if (count($this->users) > 1): ?>
					sortList: [[1,0],[2,0]]
				<?php else: ?>
					sortList: [[2,1],[1,0]]
				<?php endif ?>
			});
		});
	</script>
<?php endif ?>
