<?php $u = $this->user ?>

<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $u['link-name']) ?>">
			<?php echo $u['visible-name'] ?>
		</a>
		`s <?php echo $this->am ?> list
	</h2>

	<div class="section-body">
		<?php if (empty($u[$this->am]['entries'])): ?>
			<p>This user doesn't seem to have anything on their list.</p>
		<?php elseif ($u[$this->am]['private']): ?>
			<p>This user has marked their list as private. No table here.</p>
		<?php else: ?>
			<div class="table">
				<table>
					<thead>
						<tr>
							<th class="ord">#</th>

							<?php echo $this->htmlHelper->tableHeadStatus() ?>
							<?php echo $this->htmlHelper->tableHeadUnique() ?>
							<?php echo $this->htmlHelper->tableHeadTitle() ?>
							<?php echo $this->htmlHelper->tableHeadScore() ?>
						</tr>
					</thead>

					<tbody>
						<?php $k = 1 ?>
						<?php foreach ($u[$this->am]['entries'] as $e): ?>
							<tr>
								<td class="ord"><?php echo $k ++ ?></td>
								<?php echo $this->htmlHelper->tableBodyStatus($e) ?>
								<?php echo $this->htmlHelper->tableBodyUnique($e) ?>
								<?php echo $this->htmlHelper->tableBodyTitle($e) ?>
								<?php echo $this->htmlHelper->tableBodyScore($e) ?>
							</tr>
						<?php endforeach ?>
					</tbody>

				</table>
			</div>
		<?php endif ?>

	</div>
</div>
