<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user['link-name']) ?>">
			<?php echo $this->user['visible-name'] ?>
		</a>
		&rsquo;s miscallenous <?php echo $this->mgHelper->amText() ?> stats
	</h2>
</div>



<div class="section subtype-dist">
	<h3>
		<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
			<i data-title="Distribution of manga types (one-shot, novel, &hellip;)"></i>
		<?php else: ?>
			<i data-title="Distribution of anime types (OVA, movie, &hellip;)"></i>
		<?php endif ?>
		Subtype distribution
	</h3>
	<div class="section-body">
		<?php if (empty($this->user[$this->am]['dist-status'])): ?>
			<p>This user doesn&rsquo;t seem to have anything on their list. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
							<span class="prefix">Total one-shots</span>
							<span class="subject">
								<?php if (empty($this->user[$this->am]['dist-subtype']['one shot'])): ?>
									0
								<?php else: ?>
									<?php echo count($this->user[$this->am]['dist-subtype']['one shot']['entries']) ?>
								<?php endif ?>
							</span>
						<?php else: ?>
							<span class="prefix">Total movies</span>
							<span class="subject">
								<?php if (empty($this->user[$this->am]['dist-subtype']['movie'])): ?>
									0
								<?php else: ?>
									<?php echo count($this->user[$this->am]['dist-subtype']['movie']['entries']) ?>
								<?php endif ?>
							</span>
						<?php endif ?>
					</div>
				</li>
			</ul>


			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->user[$this->am]['dist-subtype'] as $k => $x): ?>
					<div class="more" data-id="<?php echo $x['text'] ?>">
						<p>
							<?php echo ucfirst($x['text']) ?>
							<?php if (!empty($x['entries'])): ?>
								&nbsp;(<?php echo count($x['entries']) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($x['entries'])): ?>
							<p>None!</p>
						<?php elseif ($this->user[$this->am]['private']): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($x['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
											<?php echo $e['full']['title'] ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user['user-safe-id'] ?> .subtype-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = this.key + ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, array_sum(array_map(function($x) { return count($x['entries']); }, $this->user[$this->am]['dist-subtype']))) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							data: <?php echo json_encode(array_map(function($x) { return [$x['text'], count($x['entries'])]; }, array_values($this->user[$this->am]['dist-subtype']))) ?>,
							point: { events: { click: function(e) {console.log(this);
								toggleWithinSections($('.subtype-dist .more[data-id=\'' + this.name + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>



<div class="section length-dist">
	<h3>
		<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
			<i data-title="Distribution of common manga length, in chapters"></i>
		<?php else: ?>
			<i data-title="Distribution of common anime length, in episodes"></i>
		<?php endif ?>
		Length distribution
	</h3>
	<div class="section-body">
		<?php if (empty($this->user[$this->am]['dist-length'])): ?>
			<p>This user doesn&rsquo;t seem to have anything completed. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
							<span class="prefix">Total volumes</span>
							<span class="subject"><?php echo $this->user[$this->am]['misc']['total-volumes'] ?></span>
						</div>
					</li>
					<li>
						<div>
							<span class="prefix">Total chapters</span>
							<span class="subject"><?php echo $this->user[$this->am]['misc']['total-chapters'] ?></span>
						<?php else: ?>
							<span class="prefix">Total episodes</span>
							<span class="subject"><?php echo $this->user[$this->am]['misc']['total-episodes'] ?></span>
						<?php endif ?>
					</div>
				</li>
			</ul>


			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->user[$this->am]['dist-length'] as $k => $x): ?>
					<div class="more" data-id="<?php echo $x['text'] ?>">
						<p>
							<?php echo ucfirst($this->mgHelper->amText()) ?> with <?php echo $x['text'] ?>&nbsp;
							<?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'chapter' : 'episode' ?>
							<?php if ($x['text'] != '1'): ?>
								s
							<?php endif ?>
							<?php if (!empty($x['entries'])): ?>
								&nbsp;(<?php echo count($x['entries']) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($x['entries'])): ?>
							<p>None!</p>
						<?php elseif ($this->user[$this->am]['private']): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($x['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
											<?php echo $e['full']['title'] ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user['user-safe-id'] ?> .length-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = '<?php echo ucfirst($this->mgHelper->amText()) ?> with ';
							text += this.key;
							text += ' <?php echo $this->am == AMModel::ENTRY_TYPE_MANGA ? 'chapter' : 'episode' ?>';
							if (this.key != '1') {
								text += 's';
							}
							text += ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, array_sum(array_map(function($x) { return count($x['entries']); }, $this->user[$this->am]['dist-length']))) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							data: <?php echo json_encode(array_map(function($x) { return [$x['text'], count($x['entries'])]; }, array_values($this->user[$this->am]['dist-length']))) ?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.length-dist .more[data-id=\'' + this.name + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>



<div class="section status-dist">
	<h3>
		<?php if ($this->am == AMModel::ENTRY_TYPE_MANGA): ?>
			<i data-title="Distribution of manga list status (reading, completed, &hellip;)"></i>
		<?php else: ?>
			<i data-title="Distribution of anime list status (watching, completed, &hellip;)"></i>
		<?php endif ?>
		Status distribution
	</h3>
	<div class="section-body">
		<?php if (empty($this->user[$this->am]['dist-status'])): ?>
			<p>This user doesn&rsquo;t seem to have anything on their list. No chart here.</p>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->user[$this->am]['dist-status'] as $k => $x): ?>
					<div class="more" data-id="<?php echo $x['text'] ?>">
						<p>
							<?php echo ucfirst($x['text']) ?> <?php echo $this->mgHelper->amText() ?>
							<?php if (!empty($x['entries'])): ?>
								&nbsp;(<?php echo count($x['entries']) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($x['entries'])): ?>
							<p>None!</p>
						<?php elseif ($this->user[$this->am]['private']): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($x['entries'] as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e['full']['id'] ?>">
											<?php echo $e['full']['title'] ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user['user-safe-id'] ?> .status-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = this.key + ' ' + '<?php echo $this->mgHelper->amText() ?>';
							text += ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, array_sum(array_map(function($x) { return count($x['entries']); }, $this->user[$this->am]['dist-status']))) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							data: <?php echo json_encode(array_map(function($x) { return [$x['text'], count($x['entries'])]; }, array_values($this->user[$this->am]['dist-status']))) ?>,
							point: { events: { click: function(e) {console.log(this);
								toggleWithinSections($('.status-dist .more[data-id=\'' + this.name + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>
