<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user->getLinkableName()) ?>">
			<?php echo $this->user->getPublicName() ?>
		</a>
		&rsquo;s miscellaneous <?php echo $this->mgHelper->amText() ?> stats
	</h2>
</div>



<div class="section subtype-dist">
	<h3>
		<?php if ($this->am == AMModel::TYPE_MANGA): ?>
			<i data-title="Distribution of manga types (one-shot, novel, &hellip;)"></i>
		<?php else: ?>
			<i data-title="Distribution of anime types (OVA, movie, &hellip;)"></i>
		<?php endif ?>
		Subtype distribution
	</h3>
	<div class="section-body">
		<?php if ($this->subTypeDistribution[$this->user->getID()]->getLargestGroupSize() == 0): ?>
			<p>This user doesn&rsquo;t seem to have anything on their list. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<?php if ($this->am == AMModel::TYPE_MANGA): ?>
							<span class="prefix">Total one-shots</span>
							<span class="subject">
								<?php echo intval ($this->subTypeDistribution[$this->user->getID()]->getGroupSize(MangaEntry::SUBTYPE_ONESHOT)) ?>
							</span>
						<?php else: ?>
							<span class="prefix">Total movies</span>
							<span class="subject">
								<?php echo intval ($this->subTypeDistribution[$this->user->getID()]->getGroupSize(AnimeEntry::SUBTYPE_MOVIE)) ?>
							</span>
						<?php endif ?>
					</div>
				</li>
			</ul>


			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->subTypeDistribution[$this->user->getID()]->getGroupsKeys() as $key): ?>
					<?php $entries = $this->subTypeDistribution[$this->user->getID()]->getGroupEntries($key) ?>
					<div class="more" data-id="<?php echo $key ?>">
						<p>
							<?php echo ChibiRegistry::getHelper('mg')->subTypeText($key) ?>
							<?php if (!empty($entries)): ?>
								&nbsp;(<?php echo count($entries) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($entries)): ?>
							<p>None!</p>
						<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($entries as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user->getRuntimeID() ?> .subtype-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = this.key + ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, $this->subTypeDistribution[$this->user->getID()]->getTotalSize()) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							<?php $dist = &$this->subTypeDistribution[$this->user->getID()] ?>
							data: <?php echo json_encode(array_map(function($key) use (&$dist) { return [ChibiRegistry::getHelper('mg')->subTypeText($key), $dist->getGroupSize($key), $key]; }, $dist->getGroupsKeys())) ?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.subtype-dist .more[data-id=\'' + this.config[2] + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>



<div class="section length-dist">
	<h3>
		<?php if ($this->am == AMModel::TYPE_MANGA): ?>
			<i data-title="Distribution of common manga length, in chapters"></i>
		<?php else: ?>
			<i data-title="Distribution of common anime length, in episodes"></i>
		<?php endif ?>
		Length distribution
	</h3>
	<div class="section-body">
		<?php if ($this->lengthDistribution[$this->user->getID()]->getLargestGroupSize() == 0): ?>
			<p>This user doesn&rsquo;t seem to have anything completed. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<?php if ($this->am == AMModel::TYPE_MANGA): ?>
							<span class="prefix">Completed volumes</span>
							<span class="subject"><?php echo $this->completedVolumes[$this->user->getID()] ?></span>
						</div>
					</li>
					<li>
						<div>
							<span class="prefix">Completed chapters</span>
							<span class="subject"><?php echo $this->completedChapters[$this->user->getID()] ?></span>
						<?php else: ?>
							<span class="prefix">Completed episodes</span>
							<span class="subject"><?php echo $this->completedEpisodes[$this->user->getID()] ?></span>
						<?php endif ?>
					</div>
				</li>
			</ul>


			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->lengthDistribution[$this->user->geTID()]->getGroupsKeys() as $key): ?>
					<?php $entries = $this->lengthDistribution[$this->user->geTID()]->getGroupEntries($key) ?>
					<div class="more" data-id="<?php echo $key ?>">
						<p>
							<?php echo ucfirst($this->mgHelper->amText()) ?> with <?php echo $key == '?' ? 'unknown number of' : $key ?>&nbsp;
							<?php echo $this->am == AMModel::TYPE_MANGA ? 'chapter' : 'episode' ?>
							<?php if ($key != '1'): ?>
								s
							<?php endif ?>
							<?php if (!empty($entries)): ?>
								&nbsp;(<?php echo count($entries) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($entries)): ?>
							<p>None!</p>
						<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($entries as $e): ?>
									<li>
										<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user->getRuntimeID() ?> .length-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = '<?php echo ucfirst($this->mgHelper->amText()) ?> with ';
							text += this.key == '?' ? 'unknown number of' : this.key;
							text += ' <?php echo $this->am == AMModel::TYPE_MANGA ? 'chapter' : 'episode' ?>';
							if (this.key != '1') {
								text += 's';
							}
							text += ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, $this->lengthDistribution[$this->user->getID()]->getTotalSize()) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							<?php $dist = &$this->lengthDistribution[$this->user->getID()] ?>
							data: <?php echo json_encode(array_map(function($key) use (&$dist) { return [strval($key), $dist->getGroupSize($key), $key]; }, $dist->getGroupsKeys())) ?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.length-dist .more[data-id=\'' + this.config[2] + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>



<div class="section status-dist">
	<h3>
		<?php if ($this->am == AMModel::TYPE_MANGA): ?>
			<i data-title="Distribution of manga list status (reading, completed, &hellip;)"></i>
		<?php else: ?>
			<i data-title="Distribution of anime list status (watching, completed, &hellip;)"></i>
		<?php endif ?>
		Status distribution
	</h3>
	<div class="section-body">
		<?php if ($this->statusDistribution[$this->user->getID()]->getLargestGroupSize() == 0): ?>
			<p>This user doesn&rsquo;t seem to have anything on their list. No chart here.</p>
		<?php else: ?>
			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<div class="wrapper wrapper-more">
				<?php foreach ($this->statusDistribution[$this->user->geTID()]->getGroupsKeys() as $key): ?>
					<?php $entries = $this->statusDistribution[$this->user->geTID()]->getGroupEntries($key) ?>
					<div class="more" data-id="<?php echo $key ?>">
						<p>
							<?php echo ChibiRegistry::getHelper('mg')->statusText($key) ?> <?php echo $this->mgHelper->amText() ?>
							<?php if (!empty($entries)): ?>
								&nbsp;(<?php echo count($entries) ?>)
							<?php endif ?>
							:
						</p>
						<?php if (empty($entries)): ?>
							<p>None!</p>
						<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
							<p>Can&rsquo;t show you titles from a private list.</p>
						<?php else: ?>
							<ul>
								<?php foreach ($entries as $e): ?>
										<li>
											<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $e->getID() ?>">
											<?php echo $e->getAMEntry()->getTitle() ?>
										</a>
									</li>
								<?php endforeach ?>
							</ul>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $this->user->getRuntimeID() ?> .status-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'pie', margin: 16 },
						tooltip: { formatter: function() {
							var text = this.key + ' ' + '<?php echo $this->mgHelper->amText() ?>';
							text += ': ' + this.y;
							var precent = this.y * 100.0 / <?php echo max(1, $this->statusDistribution[$this->user->getID()]->getTotalSize()) ?>;
							text += ' (' + Math.round(precent * 100) / 100 + '%)';
							return text; } },
						series: [ {
							<?php $dist = &$this->statusDistribution[$this->user->getID()] ?>
							data: <?php echo json_encode(array_map(function($key) use (&$dist) { return [ChibiRegistry::getHelper('mg')->statusText($key), $dist->getGroupSize($key), $key]; }, $dist->getGroupsKeys())) ?>,
							point: { events: { click: function(e) {
								toggleWithinSections($('.status-dist .more[data-id=\'' + this.config[2] + '\']'), true);
							} } }
						} ],
						plotOptions: { column: { pointWidth: 17 } }
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>
