<div class="user-pic">
	<!-- profile picture -->
	<?php if ($this->user->isAnonymous() or $this->user->getUserData()->getProfilePictureURL() == null): ?>
		<img class="unavailable" alt="No profile picture" src="<?php echo UrlHelper::url('media/img/pixel.gif') ?>">
	<?php else: ?>
		<img alt="Profile picture" src="<?php echo $this->user->getUserData()->getProfilePictureURL() ?>">
	<?php endif ?>
</div>



<div class="section basic">
	<!-- user name -->
	<h2>
		<a href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl(null, null, [], $this->user->getLinkableName()) ?>">
			<?php echo $this->user->getPublicName() ?>
		</a>

		<span class="updated tooltipable" data-position-my="left center" data-position-at="right center" data-title="Time of last data update">
			<?php echo date('M d, H:i', $this->user->getGenerationTime()) ?> UTC
		</span>
	</h2>

	<div class="section-body">
		<!-- basic information -->
		<dl>

			<dt>Gender</dt>
			<?php if (!$this->user->isAnonymous()): ?>
				<?php if ($this->user->getUserData()->getGender() == UserData::GENDER_FEMALE): ?>
					<dd>Female</dd>
				<?php elseif ($this->user->getUserData()->getGender() == UserData::GENDER_MALE): ?>
					<dd>Male</dd>
				<?php else: ?>
					<dd>Unknown</dd>
				<?php endif ?>
			<?php else: ?>
				<dd>Unknown</dd>
			<?php endif ?>

			<dt>List views</dt>
			<dd><?php echo $this->user->getList($this->am)->getViewCount() ?></dd>

			<dt>Time on MAL</dt>
			<?php if (intval($this->user->getUserData()->getJoinDate())): ?>
				<?php
					list ($year, $month, $day) = explode ('-', $this->user->getUserData()->getJoinDate());
					$time = mktime(0, 0, 0, $month, $day, $year);
					$diff = time() - $time;
					$diff /= 3600 * 24;
				?>
				<dd><?php printf('%.1f', $diff / 361.25) ?> years</dd>
			<?php else: ?>
				<dd>Unknown</dd>
			<?php endif ?>

		</dl>

		<!-- links to mal -->
		<ul class="mal">
			<?php if ($this->user->isAnonymous()): ?>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL profile
					</a>
				</li>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL anime list
					</a>
				</li>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL manga list
					</a>
				</li>

			<?php else: ?>
				<li>
					<a href="http://myanimelist.net/profile/<?php echo $this->user->getUserName() ?>">
						<i class="icon-pop-out"></i>
						MAL profile
					</a>
				</li>
				<li>
					<a href="http://myanimelist.net/animelist/<?php echo $this->user->getUserName() ?>">
						<i class="icon-pop-out"></i>
						MAL anime list
					</a>
				</li>
				<li>
					<a href="http://myanimelist.net/mangalist/<?php echo $this->user->getUserName() ?>">
						<i class="icon-pop-out"></i>
						MAL manga list
					</a>
				</li>
			<?php endif ?>
		</ul>

	</div>
	<div class="clear"></div>
</div>
		<div class="clear"></div>



<!-- friends -->
<div class="section">
	<h3>Friends (<?php echo count($this->user->getFriends()) ?>)</h3>
	<div class="section-body">
		<?php if (count($this->user->getFriends()) == 0): ?>
			<p>This user has no friends on MAL. :(</p>
		<?php elseif ($this->user->isAnonymous()): ?>
			<p>This user wanted to be anonymous, so their friend aren&rsquo;t shown.</p>
		<?php else: ?>
			<div class="friends scrollable">
				<?php $friends = $this->user->getFriends() ?>
				<?php usort($friends, function($a, $b) { return strlen($a->getName()) > strlen($b->getName()); }) ?>
				<ul>
					<?php foreach ($friends as $friend): ?>
						<li>
							<a class="mg waitable" href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl(null, null, [], [reset($this->userNames), $friend->getName()]) ?>">
								<i class="icon-mg"></i>
							</a>
							<a class="mal" href="http://myanimelist.net/profile/<?php echo $friend->getName() ?>">
								<span><?php echo $friend->getName() ?></span>
							</a>
						</li>
					<?php endforeach ?>
				</ul>
			</div>
		<?php endif ?>
	</div>
</div>



<!-- clubs -->
<div class="section">
	<h3>Clubs (<?php echo count($this->user->getClubs()) ?>)</h3>
	<div class="section-body">
		<?php if (count($this->user->getClubs()) == 0): ?>
			<p>This user doesn&rsquo;t belong to any clubs.</p>
		<?php elseif ($this->user->isAnonymous()): ?>
			<p>Neither wlil we tell you their clubs.</p>
		<?php else: ?>
			<div class="clubs scrollable">
				<?php $clubs = $this->user->getClubs() ?>
				<?php usort($clubs, function($a, $b) { return strlen($a->getName()) > strlen($b->getName()); }) ?>
				<ul>
					<?php foreach ($clubs as $club): ?>
						<li>
							<a href="http://myanimelist.net/clubs.php?cid=<?php echo $club->getID() ?>">
								<i class="icon-club"></i>
								<span><?php echo $club->getName() ?></span>
							</a>
						</li>
					<?php endforeach ?>
				</ul>
			</div>
		<?php endif ?>
	</div>
</div>
