<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section basic">
	<h2>
		<?php echo ChibiRegistry::getHelper('mg')->headerLink($user, 'profile', true) ?>
		<span class="updated" data-tooltip="Time of last data update" data-date="<?php echo date('c', $user->getGenerationTime()) ?>">
			<?php echo date('M d, H:i', $user->getGenerationTime()) ?> UTC
		</span>
		<div class="clear"></div><!-- fix for small pages -->
	</h2>

	<div class="section-body">
		<dl>

			<dt>Gender</dt>
			<?php if (!$user->isAnonymous()): ?>
				<?php if ($user->getUserData()->getGender() == UserData::GENDER_FEMALE): ?>
					<dd>Female</dd>
				<?php elseif ($user->getUserData()->getGender() == UserData::GENDER_MALE): ?>
					<dd>Male</dd>
				<?php else: ?>
					<dd>Unknown</dd>
				<?php endif ?>
			<?php else: ?>
				<dd>Unknown</dd>
			<?php endif ?>

			<dt>List views</dt>
			<dd class="list-views">
				<?php echo $user->getList(AMModel::TYPE_ANIME)->getViewCount() + $user->getList(AMModel::TYPE_MANGA)->getViewCount() ?>&nbsp;
				<span class="suffix">(
					<span data-tooltip="Anime list view count"><?php echo $user->getList(AMModel::TYPE_ANIME)->getViewCount() ?></span>
					+
					<span data-tooltip="Manga list view count"><?php echo $user->getList(AMModel::TYPE_MANGA)->getViewCount() ?></span>
				)</span>
			</dd>

			<dt>Time on MAL</dt>
			<?php if (intval($user->getUserData()->getJoinDate())): ?>
				<?php
					list ($year, $month, $day) = explode ('-', $user->getUserData()->getJoinDate());
					$time = mktime(0, 0, 0, $month, $day, $year);
					$diff = time() - $time;
					$diff /= 3600 * 24;
				?>
				<dd><?php printf('%.1f', $diff / 361.25) ?> years</dd>
			<?php else: ?>
				<dd>Unknown</dd>
			<?php endif ?>

		</dl>

		<ul class="mal-links">
			<?php if ($user->isAnonymous()): ?>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL profile
					</a>
				</li>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL anime list
					</a>
				</li>
				<li>
					<a href="#">
						<i class="icon-pop-out"></i>
						MAL manga list
					</a>
				</li>

			<?php else: ?>
				<li>
					<a href="http://myanimelist.net/profile/<?php echo $user->getUserName() ?>">
						<i class="icon-pop-out"></i>
						MAL profile
					</a>
				</li>
				<li>
					<a href="http://myanimelist.net/animelist/<?php echo $user->getUserName() ?><?php if (ChibiConfig::getInstance()->misc->sendReferrer) echo '&amp;sclick=1'; ?>">
						<i class="icon-pop-out"></i>
						MAL anime list
					</a>
				</li>
				<li>
					<a href="http://myanimelist.net/mangalist/<?php echo $user->getUserName() ?><?php if (ChibiConfig::getInstance()->misc->sendReferrer) echo '&amp;sclick=1'; ?>">
						<i class="icon-pop-out"></i>
						MAL manga list
					</a>
				</li>
			<?php endif ?>
		</ul>

	</div>
	<div class="clear"></div>
</div>
<?php }); ?>



<?php foreach (AMModel::getTypes() as $type): ?>
	<div class="sub-stats-wrapper">
	<?php iterateUsers(function($user, $otherUser) use ($type) { ?>
	<?php $profileInfo = $this->profileInfo[$user->getRuntimeID()][$type] ?>
	<div class="section sub-stats" data-am="<?php echo ChibiRegistry::getHelper('mg')->textAM($type) ?>">
		<h2><?php echo ChibiRegistry::getHelper('mg')->headerLink($user, ChibiRegistry::getHelper('mg')->textAM($type) . ' summary') ?></h2>
		<div class="section-body">
			<?php if ($profileInfo->completed > 0): ?>
				<div class="table-wrapper">
					<table class="tablesorter">
						<thead>
							<tr>
								<th>Type</th>
								<th>Count</th>
								<th data-tooltip="Mean score">Score</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($profileInfo->subTypeDistribution->getGroupsKeys() as $key): ?>
								<tr data-sub-type="<?php echo $key ?>">
									<td><?php echo ucfirst(ChibiRegistry::getHelper('mg')->textSubType($key)) ?></td>
									<td><?php echo $profileInfo->subTypeDistribution->getGroupSize($key) ?></td>
									<td><?php echo sprintf('%.02f', UserListService::getMeanScore($profileInfo->subTypeDistribution->getGroupEntries($key))) ?></td>
								</tr>
							<?php endforeach ?>
						</tbody>
					</table>
				</div>
			<?php endif ?>

			<dl>
				<dt>Completed</dt>
				<dd><?php echo $profileInfo->completed ?></dd>

				<dt>Franchises</dt>
				<dd><?php echo count($profileInfo->franchises) ?> <a class="franchises" href="#">(show full list)</a></dd>

				<?php if ($type == AMModel::TYPE_ANIME): ?>
					<dt>Episodes</dt>
				<?php elseif ($type == AMModel::TYPE_MANGA): ?>
					<dt>Chapters</dt>
				<?php endif ?>
				<dd>
					<?php echo $profileInfo->eps ?>
					<?php if (!empty($profileInfo->epsMismatched)): ?>
						&nbsp;<a class="mismatched-eps" href="#">(mismatch!)</a>
					<?php endif ?>
				</dd>

				<dt>Mean score</dt>
				<dd>
					<?php if ($profileInfo->scoreDistribution->getRatedCount() == 0): ?>
						-
					<?php else: ?>
						<?php printf('%.02f', $profileInfo->scoreDistribution->getMeanScore()) ?>
					<?php endif ?>
				</dd>
			</dl>

			<p>You've&#32;
				<?php if ($type == AMModel::TYPE_ANIME): ?>
					watched
				<?php elseif ($type == AMModel::TYPE_MANGA): ?>
					read
				<?php endif ?>&#32;
				<?php $diff = $profileInfo->scoreDistribution->getMeanScore() - $this->globalInfo->getAMData($type)->getScoreDistribution()->getMeanScore() ?>
				<strong><?php printf('%.02f', $profileInfo->completed * 100.0 / max(1, $this->globalInfo->getAMData($type)->getDBSize())) ?>%</strong> of all <?php echo ChibiRegistry::getHelper('mg')->textAM($type) ?> on MAL
				<?php if ($profileInfo->scoreDistribution->getRatedCount() > 0): ?>
					&#32;and your ratings are <strong><?php printf('%.02f', abs($diff)) ?></strong> points <strong><?php echo $diff < 0 ? 'lower' : 'higher' ?></strong> than global average.
				<?php else: ?>
					.
				<?php endif ?>
			</p>

			<div class="clear"></div>
		</div>

	</div>
	<?php }); ?>
	<?php iterateUsers(function($user, $otherUser) use ($type) { ?>
		<div class="wrapper-more">
		</div>
	<?php }); ?>
	</div>
<?php endforeach ?>



<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section friends">
	<h2><?php echo ChibiRegistry::getHelper('mg')->headerLink($user, 'friends (' . count($user->getFriends()) . ')') ?></h2>
	<div class="section-body">
		<?php if ($user->isAnonymous()): ?>
			<p>This user wanted to be anonymous, so their friends aren&rsquo;t shown.</p>
		<?php elseif (count($user->getFriends()) == 0): ?>
			<p>This user has no friends on MAL. :(</p>
		<?php else: ?>
			<div class="scrollable">
				<?php $friends = $user->getFriends() ?>
				<?php usort($friends, function($a, $b) { return strcasecmp($a->getName(), $b->getName()); }) ?>
				<ul>
					<?php foreach ($friends as $friend): ?>
						<li>
							<a class="mg waitable" href="<?php echo ChibiRegistry::getHelper('mg')->constructUrl(null, null, [], [reset($this->userNames), $friend->getName()]) ?>">
								<i class="icon-mg"></i>
								<span><?php echo $friend->getName() ?></span>
							</a>
						</li>
					<?php endforeach ?>
				</ul>
				<div class="clear"></div>
			</div>
		<?php endif ?>
	</div>
</div>
<?php }); ?>



<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section clubs">
	<h2><?php echo ChibiRegistry::getHelper('mg')->headerLink($user, 'clubs (' . count($user->getClubs())  . ')') ?></h2>
	<div class="section-body">
		<?php if ($user->isAnonymous()): ?>
			<p>Neither will we tell you their clubs.</p>
		<?php elseif (count($user->getClubs()) == 0): ?>
			<p>This user doesn&rsquo;t belong to any clubs.</p>
		<?php else: ?>
			<div class="scrollable">
				<?php $clubs = $user->getClubs() ?>
				<?php usort($clubs, function($a, $b) { return strcasecmp($a->getName(), $b->getName()); }) ?>
				<ul>
					<?php foreach ($clubs as $club): ?>
						<li>
							<a href="http://myanimelist.net/clubs.php?cid=<?php echo $club->getID() ?>">
								<i class="icon-club"></i>
								<span><?php echo $club->getName() ?></span>
							</a>
						</li>
					<?php endforeach ?>
				</ul>
				<div class="clear"></div>
			</div>
		<?php endif ?>
	</div>
</div>
<?php }); ?>

<script type="text/javascript">
	$('.clubs li').width(Math.floor($('.clubs').width() / 2 - 20));
	$('.friends li').width(Math.floor($('.friends').width() / 3 - 20));
</script>
