<?php $u = $this->user ?>

<div class="section">
	<h2>
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $u['link-name']) ?>">
			<?php echo $u['visible-name'] ?>
		</a>
		`s <?php echo $this->am ?> rating statistics
	</h2>
</div>

<div class="section score-dist">
	<h3>
		<i data-title="Count of all entries scored with given rating, in a bar chart form" class="tooltipable icon-tooltip"></i>
		Rating distribution
	</h3>
	<div class="section-body">
		<?php if ($u[$this->am]['score-info']['rated'] == 0): ?>
			<p>This user doesn't seem to have anything rated. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<span class="prefix">Total rated</span>
						<span class="subject"><?php printf('%d', $u[$this->am]['score-info']['rated']) ?></span>
					</div>
				</li>
				<li>
					<div>
						<span class="prefix">Mean score</span>
						<span class="subject"><?php printf('%.02f', $u[$this->am]['score-info']['mean']) ?></span>
					</div>
				</li>
				<li>
					<div>
						<span class="prefix">Std dev</span>
						<span class="subject"><?php printf('%.02f',$u[$this->am]['score-info']['std-dev']) ?></span>
					</div>
				</li>
			</ul>

			<div class="wrapper wrapper-target">
				<div class="target"></div>
				<div class="clear"></div>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $u['user-id'] ?> .score-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'bar', marginRight: 35 },
						xAxis: { categories: <?php echo json_encode(array_map(function($x) { return $x == 0 ? '-' : $x; }, array_keys($u[$this->am]['score-time-dist']))) ?>, title: { text: 'Rating' } },
						yAxis: { title: { text: 'Count', margin: 15 } },
						tooltip: { formatter: function() {
							var text;
							if (this.x == '-') {
								text = 'Unrated titles: ' + this.y;
							} else {
								text = 'Titles rated with ' + this.x + ': ' + this.y;
							}
							var percent = this.y * 100.0 / <?php echo max(1, $u[$this->am]['score-info']['rated'] + $u[$this->am]['score-info']['unrated']) ?>;
							text = text + ' (' + (Math.round(percent * 100.0) / 100.0) + '%)';
							return text;
						} },
						series: [ { data: <?php echo json_encode(array_values($u[$this->am]['score-dist'])) ?> } ]
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>

<div class="section score-time-dist">
	<h3>
		<i data-title="How much time have you spent on titles rated with given score?" class="tooltipable icon-tooltip"></i>
		Rating to time distribution
	</h3>
	<div class="section-body">
		<?php if ($u[$this->am]['score-info']['rated'] == 0): ?>
			<p>This user doesn't seem to have anything rated. No chart here.</p>
		<?php else: ?>
			<ul class="infobox">
				<li>
					<div>
						<span class="prefix">Total time</span>
						<span class="subject"><?php printf('%.02f', ($u[$this->am]['score-info']['rated-total-time'] + $u[$this->am]['score-info']['unrated-total-time']) / 24.0) ?></span>
						<span class="suffix">days</span>
					</div>
				</li>
			</ul>

			<div class="wrapper wrapper-target">
				<div id="target-score-time-dist-<?php echo $u['user-id'] ?>" class="target"></div>
				<div class="clear"></div>
			</div>

			<script type="text/javascript">
				$('#user-<?php echo $u['user-id'] ?> .score-time-dist .target').each(function() {
					var chart = new Highcharts.Chart({
						chart: { renderTo: this, type: 'bar', marginRight: 15 },
						xAxis: { categories: <?php echo json_encode(array_map(function($x) { return $x == 0 ? '-' : $x; }, array_keys($u[$this->am]['score-time-dist']))) ?>, title: { text: 'Rating' } },
						yAxis: { title: {text: 'Hours spent', margin: 15 } },
						tooltip: { formatter: function() {
							var text;
							if (this.x == '-') {
								text = 'Hours spent on unrated titles: ' + Math.round(this.y * 100) / 100.0;
							} else {
								text = 'Hours spent on titles rated with ' + this.x + ': ' + Math.round(this.y * 100) / 100.0;
							}
							var percent = this.y * 100.0 / <?php echo max(1, $u[$this->am]['score-info']['rated-total-time'] + $u[$this->am]['score-info']['unrated-total-time']) ?>;
							text = text + ' (' + (Math.round(percent * 100.0) / 100.0) + '%)';
							return text
						} },
						series: [ { data: <?php echo json_encode(array_values($u[$this->am]['score-time-dist'])) ?> } ]
					});
				});
			</script>
		<?php endif ?>
	</div>
</div>

<div class="section unrated">
	<h3>Unrated titles</h3>
	<div class="section-body">
		<?php if ($u[$this->am]['score-info']['unrated'] == 0): ?>
			<p>This user doesn't seem to have anything unrated. No table here.</p>
		<?php elseif ($u[$this->am]['private']): ?>
			<p>This user has marked their list as private. No table here.</p>
		<?php else: ?>
			<table>
				<thead>
					<tr>
						<th class="ord">#</th>
						<?php echo $this->htmlHelper->tableHeadStatus() ?>
						<?php echo $this->htmlHelper->tableHeadUnique() ?>
						<?php echo $this->htmlHelper->tableHeadTitle() ?>
						<?php echo $this->htmlHelper->tableHeadLength() ?>
					</tr>
				</thead>

				<tbody>
					<?php $k = 1 ?>
					<?php foreach ($u[$this->am]['score-info']['unrated-titles'] as $e): ?>
						<tr>
							<td class="ord"><?php echo $k ++ ?></td>
							<?php echo $this->htmlHelper->tableBodyStatus($e) ?>
							<?php echo $this->htmlHelper->tableBodyUnique($e) ?>
							<?php echo $this->htmlHelper->tableBodyTitle($e) ?>
							<?php echo $this->htmlHelper->tableBodyLength($e) ?>
						</tr>
					<?php endforeach ?>
				</tbody>

			</table>
		<?php endif ?>
	</div>
</div>
