<?php iterateUsers(function($user, $otherUser) { ?>
<div class="section missing">
	<h2>
		<i data-title="List of titles related to those you completed, sorted by score." class="tooltipable icon-tooltip"></i>
		<?php if (count($this->users) > 1): ?>
			Missing titles for <a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $user->getLinkableName()) ?>">
				<?php echo $user->getPublicName() ?>
			</a>
		<?php else: ?>
			Missing titles
		<?php endif ?>
	</h2>
	<div class="section-body">

		<?php if (empty($this->proposedEntries[$user->getID()])): ?>
			<p>Yay! No missing relations!</p>
		<?php elseif ($user->getList($this->am)->isPrivate()): ?>
			<p>Since <?php echo $user->getPublicName() ?>&rsquo;s <?php echo $this->mgHelper->amText() ?> list is marked as private, we can&rsquo;t reveal its content by showing suggestions.<br>
			If this is your list, click <a href="http://myanimelist.net/editprofile.php?go=listpreferences">here</a> to change privacy settings.</p>
		<?php else: ?>

			<table>
				<thead>
					<tr>
						<td>You've <?php echo $this->am == AMModel::TYPE_ANIME ? 'watched' : 'read' ?> this&hellip;</td>
						<td>&hellip;so you might want to check this:</td>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->proposedEntries[$user->getID()] as $data): ?>
						<tr id="sug-row-<?php echo $this->am ?>-<?php echo $data['entry']->getID() ?>">
							<td class="subject">
								<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $data['entry']->getID() ?>">
									<?php echo htmlspecialchars($data['entry']->getAMEntry()->getTitle()) ?>
								</a>
							</td>
							<td class="proposed">
								<ul>
									<?php foreach ($data['entries'] as $subEntry): ?>
										<?php if (!$subEntry->getTitle()): ?>
											<?php continue ?>
										<?php else: ?>
											<li id="sug-elem-<?php echo $this->mgHelper->amText() ?>-<?php echo $subEntry->getID() ?>">
												<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $subEntry->getID() ?>">
													<?php echo htmlspecialchars($subEntry->getTitle()) ?>
												</a>
											</li>
										<?php endif ?>
									<?php endforeach ?>
								</ul>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		<?php endif ?>

	</div>
</div>
<?php }); ?>
