<div class="section">
	<h2>
		<?php echo ucfirst($this->mgHelper->amText()) ?> suggestions for&nbsp;
		<a href="<?php echo $this->mgHelper->constructUrl(null, null, [], $this->user->getLinkableName()) ?>">
			<?php echo $this->user->getPublicName() ?>
		</a>
	</h2>
</div>



<div class="section missing">
	<h3>
		<i data-title="List of titles related to those you completed, sorted by score." class="tooltipable icon-tooltip"></i>
		Missing titles
	</h3>
	<div class="section-body">

		<?php if (empty($this->proposedEntries[$this->user->getID()])): ?>
			<p>Yay! No missing relations!</p>
		<?php elseif ($this->user->getList($this->am)->isPrivate()): ?>
			<p>Since <?php echo $this->user->getPublicName() ?>&rsquo;s <?php echo $this->mgHelper->amText() ?> list is marked as private, we can&rsquo;t reveal its content by showing suggestions.<br>
			If this is your list, click <a href="http://myanimelist.net/editprofile.php?go=listpreferences">here</a> to change privacy settings.</p>
		<?php else: ?>

			<table>
				<thead>
					<tr>
						<td>Suggested&hellip;</td>
						<td>&hellip;because of:</td>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->proposedEntries[$this->user->getID()] as $data): ?>
						<tr id="sug-row-<?php echo $this->am ?>-<?php echo $data['entry']->getID() ?>">
							<td class="proposed">
								<ul>
									<?php foreach ($data['entries'] as $subEntry): ?>
										<?php if (!$subEntry->getTitle()): ?>
											<?php trigger_error('Invalid entry ' . json_encode($subEntry->getID()) . ' for user ' . $this->user->getPublicName(), E_USER_WARNING) ?>
											<?php continue ?>
										<?php else: ?>
											<li id="sug-elem-<?php echo $this->mgHelper->amText() ?>-<?php echo $subEntry->getID() ?>">
												<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $subEntry->getID() ?>">
													<?php echo htmlspecialchars($subEntry->getTitle()) ?>
												</a>
											</li>
										<?php endif ?>
									<?php endforeach ?>
								</ul>
							</td>
							<td class="subject">
								<a href="http://myanimelist.net/<?php echo $this->mgHelper->amText() ?>/<?php echo $data['entry']->getID() ?>">
									<?php echo htmlspecialchars($data['entry']->getAMEntry()->getTitle()) ?>
								</a>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		<?php endif ?>

	</div>
</div>
